# Name : Anjali Suresh Chopade
# Roll_No :2013

# Section 1: Conceptual Foundations

In [3]:
import numpy as np
import pandas as pd

print("Pandas version:", pd.__version__) 
print("NumPy version:", np.__version__)

Pandas version: 2.3.1
NumPy version: 2.4.6

In [4]:
# QUick illustration: same data, four containers 
data = ['Banana', 5, 4.3]

py_list = data
py_dict = {'item': 'banana', 'count': 5, 'price': 4.3}
np_arr = np.array(data, dtype=object)
pd_series = pd.Series(data, index=['item', 'count', 'price'])

print("List:", py_list) 
print("Dict:", py_dict) 
print("NumPy array:", np_arr)
print("\nPandas Series (labeled, mixed types):") 
print(pd_series)

List: ['Banana', 5, 4.3]
Dict: {'item': 'banana', 'count': 5, 'price': 4.3}
NumPy array: ['Banana' 5 4.3]

Pandas Series (labeled, mixed types):
item     Banana
count         5
price       4.3
dtype: object

# Section 2: Pandas Series

In [5]:
# Create a Series from a list (default integer index)
lst = ['Banana', 5]
s = pd.Series(lst)
print(s)
print(type(s))

0    Banana
1         5
dtype: object
<class 'pandas.core.series.Series'>

In [6]:
# Create a Series with a custom index 
lst = ['Banana', 5]
s = pd.Series(lst, index=['a', 'c']) 
print(s)

a    Banana
c         5
dtype: object

In [7]:
# Create a Series with a custom index
lst = ['Banana', 5]
s = pd.Series(lst, index=['a', 'c']) 
print(s)

a    Banana
c         5
dtype: object

In [8]:
# Create a Series from a NumPy array
a = np.array(['Apple', 50])
print(a, type(a))

s = pd.Series(a, index=['a', 'b'])
print(s)

['Apple' '50'] <class 'numpy.ndarray'>
a    Apple
b       50
dtype: object

In [9]:
# Create a Series from a dictionary -> keys become the index 
d = {'a': [10, 20, 30], 'b': [30, 20, 10]}
s = pd.Series(d)
print(s)

a    [10, 20, 30]
b    [30, 20, 10]
dtype: object

In [10]:
# Indexing into a Series
s = pd.Series([1, 2, 3, 4],
index=['a', 'n', 's', 'h'])
print("By label:", s['a'])
print("By position:", s.iloc[1])
print("Slice by label:\n", s['n':'h'])	# label slicing is INCLUSIVE print(“Slice by position:\n”, s.iloc[1:3])
# positional slicing is EXCLUSIVE of end

By label: 1
By position: 2
Slice by label:
 n    2
s    3
h    4
dtype: int64

# Section 3: DataFrame Creation

In [11]:
# Create DataFrame from a dictionary 
s = {'coll': [10, 20]}
df_dict = pd.DataFrame(s)
print(df_dict)
print(type(df_dict)) 
print("Shape:", df_dict.shape)

   coll
0    10
1    20
<class 'pandas.core.frame.DataFrame'>
Shape: (2, 1)

In [12]:
# Create DataFrame from a dictionary
s = {'coll': [11, 22]}
df_dict = pd.DataFrame(s) 
print(df_dict) 
print(type(df_dict))
print("Shape:", df_dict.shape)

   coll
0    11
1    22
<class 'pandas.core.frame.DataFrame'>
Shape: (2, 1)

In [13]:
# Create DataFrame from a dictionary of equal-length lists (most common pattern)
df_multi = pd.DataFrame({
'name': ['Alisha', 'Rohan', 'Mahi'],
'age'  : [20, 21, 11],
'score' : [8.5, 2.0, 7.3]})
df_multi

     name  age  score
0  Alisha   20    8.5
1   Rohan   21    2.0
2    Mahi   11    7.3

# Section 4: Combining DataFrames

In [14]:
temp_df = pd.DataFrame({
    'city': ['Pune', 'Nagpur', 'Nashik', 'Kolhapur'],
    'temp': [30, 38, 29, 31]
})

hum_df = pd.DataFrame({
    'city': ['Pune', 'Nagpur', 'Aurangabad', 'Solapur'],
    'humidity': [72, 58, 65, 60]
})

print(temp_df)
print()
print(hum_df)

       city  temp
0      Pune    30
1    Nagpur    38
2    Nashik    29
3  Kolhapur    31

         city  humidity
0        Pune        72
1      Nagpur        58
2  Aurangabad        65
3     Solapur        60

In [15]:
# concat: stacks rows on top of each other (note duplicate index unless ignore_index=True)
pd.concat([temp_df, hum_df],
ignore_index=True)

         city  temp  humidity
0        Pune  30.0       NaN
1      Nagpur  38.0       NaN
2      Nashik  29.0       NaN
3    Kolhapur  31.0       NaN
4        Pune   NaN      72.0
5      Nagpur   NaN      58.0
6  Aurangabad   NaN      65.0
7     Solapur   NaN      60.0

In [16]:
# concat along columns (axis=1) - aligns by index position
pd.concat([temp_df, hum_df], axis=1)

       city  temp        city  humidity
0      Pune    30        Pune        72
1    Nagpur    38      Nagpur        58
2    Nashik    29  Aurangabad        65
3  Kolhapur    31     Solapur        60

In [17]:
# merge: outer join keeps ALL keys from both sides, filling NaN where unmatched
pd.merge(temp_df, hum_df, on='city', how='outer')

         city  temp  humidity
0  Aurangabad   NaN      65.0
1    Kolhapur  31.0       NaN
2      Nagpur  38.0      58.0
3      Nashik  29.0       NaN
4        Pune  30.0      72.0
5     Solapur   NaN      60.0

In [18]:
# merge: inner join keeps ONLY keys present in both DataFrames 
pd.merge(temp_df, hum_df, on='city', how='inner')

     city  temp  humidity
0    Pune    30        72
1  Nagpur    38        58

In [19]:
# merge: left / right joins
print(pd.merge(temp_df, hum_df, on='city', how='left')) 
print()
print(pd.merge(temp_df, hum_df, on='city', how='right'))

       city  temp  humidity
0      Pune    30      72.0
1    Nagpur    38      58.0
2    Nashik    29       NaN
3  Kolhapur    31       NaN

         city  temp  humidity
0        Pune  30.0        72
1      Nagpur  38.0        58
2  Aurangabad   NaN        65
3     Solapur   NaN        60

In [20]:
# join: merges on the INDEX instead of a column
left = temp_df.set_index('city') 
right = hum_df.set_index('city') 
left.join(right, how='outer')

            temp  humidity
city
Aurangabad   NaN      65.0
Kolhapur    31.0       NaN
Nagpur      38.0      58.0
Nashik      29.0       NaN
Pune        30.0      72.0
Solapur      NaN      60.0

# Section 5: Importing / Exporting Data

In [21]:
# --- Build a synthetic student dataset ---

np.random.seed(42)
n = 200

df = pd.DataFrame({
    'Student_ID': np.arange(1, n + 1),
    'Age': np.random.randint(17, 25, n),
    'Gender': np.random.choice(['Male', 'Female'], n, p=[0.55, 0.45]),
    'Maths': np.random.randint(35, 101, n),
    'Science': np.random.randint(35, 101, n),
    'English': np.random.randint(35, 101, n),
    'Attendance': np.round(np.random.uniform(60, 100, n), 1),
    'Study_Hours': np.round(np.random.uniform(1, 8, n), 1),
    'Sports': np.random.choice(['Yes', 'No'], n, p=[0.4, 0.6]),
    'Result': np.random.choice(['Pass', 'Fail'], n, p=[0.85, 0.15])
})

# Inject a few missing values and duplicate rows
df.loc[[5, 18, 50, 95], 'Study_Hours'] = np.nan
df = pd.concat([df, df.iloc[[10, 10, 25]]], ignore_index=True)

print(df.shape)
print(df.head())

(203, 10)
   Student_ID  Age  Gender  Maths  Science  English  Attendance  Study_Hours  \
0           1   23    Male     81       94       54        66.2          2.7
1           2   20  Female     89       84       46        67.3          1.8
2           3   21    Male     74       62       81        94.5          3.5
3           4   23    Male     86       75       35        97.8          3.0
4           5   19  Female     50       98       48        74.9          3.1

  Sports Result
0    Yes   Fail
1     No   Pass
2     No   Fail
3    Yes   Pass
4     No   Pass

In [22]:
# Export to CSV / Excel / JSON

df.to_csv('student_data.csv', index=False)
df.to_excel('student_data.xlsx', index=False)
df.to_json('student_data.json', orient='records')

print("Files written: student_data.csv / .xlsx / .json")

# Read them back

df_csv = pd.read_csv('student_data.csv')
df_xlsx = pd.read_excel('student_data.xlsx')
df_json = pd.read_json('student_data.json')

print(df_csv.shape, df_xlsx.shape, df_json.shape)

df_csv.head(3)

Files written: student_data.csv / .xlsx / .json
(203, 10) (203, 10) (203, 10)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
1,2,20,Female,89,84,46,67.3,1.8,No,Pass
2,3,21,Male,74,62,81,94.5,3.5,No,Fail

# Section 6: DataFrame Attributes

In [23]:
print("shape:", df.shape)
print("size:", df.size)
print("ndim:", df.ndim)
print(df)

shape: (203, 10)
size: 2030
ndim: 2
     Student_ID  Age  Gender  Maths  Science  English  Attendance  \
0             1   23    Male     81       94       54        66.2
1             2   20  Female     89       84       46        67.3
2             3   21    Male     74       62       81        94.5
3             4   23    Male     86       75       35        97.8
4             5   19  Female     50       98       48        74.9
..          ...  ...     ...    ...      ...      ...         ...
198         199   21  Female     42       60       72        76.9
199         200   19    Male     92       53       85        89.5
200          11   19    Male     53       47       67        88.6
201          11   19    Male     53       47       67        88.6
202          26   22    Male     98       45       43        94.2

     Study_Hours Sports Result
0            2.7    Yes   Fail
1            1.8     No   Pass
2            3.5     No   Fail
3            3.0    Yes   Pass
4            3.1     No   Pass
..           ...    ...    ...
198          1.1     No   Fail
199          1.5    Yes   Fail
200          3.7    Yes   Pass
201          3.7    Yes   Pass
202          5.5    Yes   Pass

[203 rows x 10 columns]

In [24]:
print("columns:", list(df.columns))
print("index:", df.index)

columns: ['Student_ID', 'Age', 'Gender', 'Maths', 'Science', 'English', 'Attendance', 'Study_Hours', 'Sports', 'Result']
index: RangeIndex(start=0, stop=203, step=1)

In [25]:
df.values[:5]	# underlying NumPy representation (loses column labels)

array([[1, 23, 'Male', 81, 94, 54, 66.2, 2.7, 'Yes', 'Fail'],
       [2, 20, 'Female', 89, 84, 46, 67.3, 1.8, 'No', 'Pass'],
       [3, 21, 'Male', 74, 62, 81, 94.5, 3.5, 'No', 'Fail'],
       [4, 23, 'Male', 86, 75, 35, 97.8, 3.0, 'Yes', 'Pass'],
       [5, 19, 'Female', 50, 98, 48, 74.9, 3.1, 'No', 'Pass']],
      dtype=object)

In [26]:
df.axes	# [row index, column index] as a list

[RangeIndex(start=0, stop=203, step=1),
 Index(['Student_ID', 'Age', 'Gender', 'Maths', 'Science', 'English',
        'Attendance', 'Study_Hours', 'Sports', 'Result'],
       dtype='object')]

In [27]:
df.keys()	# same as df.columns for a DataFrame

Index(['Student_ID', 'Age', 'Gender', 'Maths', 'Science', 'English',
       'Attendance', 'Study_Hours', 'Sports', 'Result'],
      dtype='object')

In [28]:
df.info()	# dtypes + non-null counts + memory usage - great first command on any new dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   203 non-null    int64
 1   Age          203 non-null    int32
 2   Gender       203 non-null    object
 3   Maths        203 non-null    int32
 4   Science      203 non-null    int32
 5   English      203 non-null    int32
 6   Attendance   203 non-null    float64
 7   Study_Hours  199 non-null    float64
 8   Sports       203 non-null    object
 9   Result       203 non-null    object
dtypes: float64(2), int32(4), int64(1), object(3)
memory usage: 12.8+ KB

In [29]:
df.describe()	# summary statistics for numeric columns (count, mean, std, min, quartiles, max)

,Student_ID,Age,Maths,Science,English,Attendance,Study_Hours
count,203.000000,203.000000,203.000000,203.000000,203.000000,203.000000,199.000000
mean,99.251232,20.551724,66.477833,67.339901,67.251232,79.928079,4.621608
std,58.356373,2.273618,19.036007,20.107575,18.816228,11.853138,2.086921
min,1.000000,17.000000,35.000000,35.000000,35.000000,60.400000,1.000000
25%,48.500000,19.000000,50.000000,51.000000,51.000000,69.600000,2.750000
50%,99.000000,20.000000,66.000000,67.000000,68.000000,80.800000,4.800000
75%,149.500000,23.000000,83.000000,85.000000,83.000000,90.000000,6.450000
max,200.000000,24.000000,100.000000,100.000000,100.000000,99.900000,8.000000

In [30]:
df.describe(include='object')	# summary stats for categorical/object columns

       Gender Sports Result
count     203    203    203
unique      2      2      2
top      Male     No   Pass
freq      109    122    177

# Section 7: Selecting & Indexing

In [31]:
	df.iloc[1]	# first row, by position

Student_ID          2
Age                20
Gender         Female
Maths              89
Science            84
English            46
Attendance       67.3
Study_Hours       1.8
Sports             No
Result           Pass
Name: 1, dtype: object

In [32]:
df.iloc[-1]

Student_ID       26
Age              22
Gender         Male
Maths            98
Science          45
English          43
Attendance     94.2
Study_Hours     5.5
Sports          Yes
Result         Pass
Name: 202, dtype: object

In [33]:
df.iloc[ [5, 8]]	# specific rows by position

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
8,9,23,Male,51,67,45,61.0,7.9,No,Pass

In [34]:
df.iloc[0:4, 0:1]	# rows 0-2, columns 0-1 (end exclusive, like Python slicing)

   Student_ID
0           1
1           2
2           3
3           4

In [35]:
df.loc[0]	# row with index label 0

Student_ID        1
Age              23
Gender         Male
Maths            81
Science          94
English          54
Attendance     66.2
Study_Hours     2.7
Sports          Yes
Result         Fail
Name: 0, dtype: object

In [36]:
df.iloc[[2, 6]]	# rows with index labels 2 and 3

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

In [37]:
df.iloc[:, 2]

0        Male
1      Female
2        Male
3        Male
4      Female
        ...
198    Female
199      Male
200      Male
201      Male
202      Male
Name: Gender, Length: 203, dtype: object

In [38]:
df.loc[[4, 8], 'Age':'Attendance']	# label-based slice (INCLUSIVE of 'TP')

   Age  Gender  Maths  Science  English  Attendance
4   19  Female     50       98       48        74.9
8   23    Male     51       67       45        61.0

In [39]:
df.loc[:, ['Maths', 'English']]	# multiple specific columns

     Maths  English
0       81       54
1       89       46
2       74       81
3       86       35
4       50       48
..     ...      ...
198     42       72
199     92       85
200     53       67
201     53       67
202     98       43

[203 rows x 2 columns]

In [40]:
# Boolean indexing
male_data = df[df['Gender'] == 'Male'] 
male_data.head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

In [41]:
# Multiple conditions: use & / I with parentheses (NOT 'and'/'or') 
df[(df['Age'] >= 7) & (df['Gender'] == 'Male')].tail()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
197,198,20,Male,70,39,100,76.7,4.2,No,Pass
199,200,19,Male,92,53,85,89.5,1.5,Yes,Fail
200,11,19,Male,53,47,67,88.6,3.7,Yes,Pass
201,11,19,Male,53,47,67,88.6,3.7,Yes,Pass
202,26,22,Male,98,45,43,94.2,5.5,Yes,Pass

In [42]:
# .query() - same filter, more readable for complex conditions 
df.query("Age >= 5 and Gender == 'Male'").head(5)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

In [43]:
# .query() - same filter, more readable for complex conditions 
df.query("Age >= 6 and Gender == 'Male'").head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

# Section 8: Sorting, Ranking, Rename, Drop, Insert, Assign,Replace

In [44]:
# Sort by a single column 
df.sort_values(by='Attendance', ascending=False).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
188,189,23,Male,88,85,83,99.9,5.8,Yes,Pass
145,146,23,Female,38,98,81,99.5,4.2,Yes,Pass
66,67,20,Male,78,100,100,99.4,1.6,Yes,Pass
195,196,18,Male,62,79,35,99.4,6.6,No,Pass
157,158,18,Female,54,68,41,98.8,7.6,Yes,Fail

In [45]:
# Sort by multiple columns
df.sort_values(by=['Gender', 'Age'], ascending=[True, False]).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
14,15,24,Female,57,81,39,69.2,6.5,No,Pass
18,19,24,Female,92,90,36,92.0,NaN,Yes,Pass
46,47,24,Female,35,38,64,85.0,2.6,No,Fail
56,57,24,Female,67,84,73,95.8,7.0,No,Pass
83,84,24,Female,58,90,91,83.9,7.1,Yes,Pass

In [46]:
# rank() - assigns a rank to each value (useful for percentile/competition-style ranking)
df['Age_rank'] = df['Age'].rank(ascending=False) 
df[['Age', 'Age_rank']].head()

   Age  Age_rank
0   23      40.0
1   20     115.5
2   21      89.0
3   23      40.0
4   19     143.0

In [47]:
# Rename columns
df_renamed = df.rename(columns={'Maths':'M1','Science':'s1'})
df_renamed.head(2)

,Student_ID,Age,Gender,M1,s1,English,Attendance,Study_Hours,Sports,Result,Age_rank
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail,40.0
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,115.5

In [48]:
# Drop columns
# Drop one column
df.drop('Age_rank', axis=1, errors='ignore', inplace=True)

# Drop multiple columns
df.drop(['Maths', 'Science'], axis=1).head(2)

   Student_ID  Age  Gender  English  Attendance  Study_Hours Sports Result
0           1   23    Male       54        66.2          2.7    Yes   Fail
1           2   20  Female       46        67.3          1.8     No   Pass

In [49]:
# Drop rows
df.drop([0, 1, 2], axis=0).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
4,5,19,Female,50,98,48,74.9,3.1,No,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail
7,8,21,Female,53,51,71,76.3,1.1,Yes,Pass

In [51]:
# Insert a column at a specific position
df = pd.read_csv("student_data.csv")   # किंवा तुझ्या file चे नाव

df_copy = df.copy()

df_copy.insert(1, 'AgeGroup',
               np.where(df_copy['Age'] >= 60, 'Senior', 'Adult'))

df_copy.head(3)

,Student_ID,AgeGroup,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,Adult,23,Male,81,94,54,66.2,2.7,Yes,Fail
1,2,Adult,20,Female,89,84,46,67.3,1.8,No,Pass
2,3,Adult,21,Male,74,62,81,94.5,3.5,No,Fail

In [54]:
# assign() - create one or more new columns in a chainable/functional style 
df_assigned = df.assign(
TB_per_DB=lambda x: x['Maths'] / (x['Science'] + 0.02),	# +0.01 avoids divide-by-zero
IsMale=lambda x: x['Gender'] == 'Male' )
df_assigned.head(3)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result,TB_per_DB,IsMale
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail,0.861519,True
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,1.059272,False
2,3,21,Male,74,62,81,94.5,3.5,No,Fail,1.193163,True

In [57]:
# replace() - swap specific values
df['Gender'].replace({'Male': 'm', })

0           m
1      Female
2           m
3           m
4      Female
        ...
198    Female
199         m
200         m
201         m
202         m
Name: Gender, Length: 203, dtype: object

# Section 9: map, apply, DataFrame.map, and Lambda Functions

In [59]:
# map() on a Series with a dictionary 
gender_code = {'Male': 2, 'Female' : 1}
df['Gender_code'] = df['Gender'].map(gender_code) 
df[['Gender', 'Gender_code']].head()

   Gender  Gender_code
0    Male            2
1  Female            1
2    Male            2
3    Male            2
4  Female            1

In [60]:
# map() with a function / lambda
df['Age_in_months'] = df['Age'].map(lambda x: x * 14) 
df[['Age', 'Age_in_months']].head()

   Age  Age_in_months
0   23            322
1   20            280
2   21            294
3   23            322
4   19            266

In [62]:
# apply() on a Series - equivalent to map() for simple functions 
df['M1'] = df['Maths'].apply(lambda x: x ** 4)
df[['Maths', 'M1']].head()

   Maths        M1
0     81  43046721
1     89  62742241
2     74  29986576
3     86  54700816
4     50   6250000

In [65]:
# apply() on a DataFrame, row-wise (axis=1)

def student_risk(row):
    if row['Maths'] < 40 or row['Attendance'] < 75:
        return 'High'
    else:
        return 'Low'

df['Risk'] = df.apply(student_risk, axis=1)

df[['Maths', 'Attendance', 'Risk']].head()

   Maths  Attendance  Risk
0     81        66.2  High
1     89        67.3  High
2     74        94.5   Low
3     86        97.8   Low
4     50        74.9  High

In [66]:
# apply() on a DataFrame, column-wise (axis=0, the default) - function receives a full column
df[['Age', 'Maths', 'Science']].apply(lambda col: col.max() - col.min())

Age         7
Maths      65
Science    65
dtype: int64

In [68]:
# DataFrame.map() - element-wise transform across the WHOLE frame (numeric columns shown here)
df[['Age', 'Maths', 'Science']].map(lambda x: round(x, 1))

     Age  Maths  Science
0     23     81       94
1     20     89       84
2     21     74       62
3     23     86       75
4     19     50       98
..   ...    ...      ...
198   21     42       60
199   19     92       53
200   19     53       47
201   19     53       47
202   22     98       45

[203 rows x 3 columns]

In [70]:
# Cleanup helper columns
df.drop(columns=['Gender_code', 'Age_in_months', 'Risk'], inplace=True, errors='ignore')

print(df.head())

   Student_ID  Age  Gender  Maths  Science  English  Attendance  Study_Hours  \
0           1   23    Male     81       94       54        66.2          2.7
1           2   20  Female     89       84       46        67.3          1.8
2           3   21    Male     74       62       81        94.5          3.5
3           4   23    Male     86       75       35        97.8          3.0
4           5   19  Female     50       98       48        74.9          3.1

  Sports Result
0    Yes   Fail
1     No   Pass
2     No   Fail
3    Yes   Pass
4     No   Pass

# Section 10: Missing Values

In [71]:
df.isnull().sum()	# count of missing values per column

Student_ID     0
Age            0
Gender         0
Maths          0
Science        0
English        0
Attendance     0
Study_Hours    4
Sports         0
Result         0
dtype: int64

In [72]:
df.isna().sum()	# isna() is an alias for isnull() - identical behavior

Student_ID     0
Age            0
Gender         0
Maths          0
Science        0
English        0
Attendance     0
Study_Hours    4
Sports         0
Result         0
dtype: int64

In [73]:
df.notnull().sum() # inverse: count of N0N-missing values per column

Student_ID     203
Age            203
Gender         203
Maths          203
Science        203
English        203
Attendance     203
Study_Hours    199
Sports         203
Result         203
dtype: int64

In [76]:
# dropna(): remove rows with ANY missing value 
print("Before:", df.shape)
print("After dropna():", df.dropna().shape)

Before: (203, 10)
After dropna(): (199, 10)

In [78]:
df['Study_Hours'].fillna(1.0).isnull().sum()

np.int64(0)

In [81]:
# fillna() with the column mean / median (common imputation strategy) 
mean_fill = df['Attendance'].fillna(df['Attendance'].mean())
median_fill = df['Attendance'].fillna(df['Attendance'].median())
print("Mean used:", df['Attendance'].mean())
print("Median used:", df['Attendance'].median())

Mean used: 79.928078817734
Median used: 80.8

In [83]:
# fillna() with a GROUPED statistic - more accurate than a single global fill value
df['Attendance']	
df.groupby('Gender')['Attendance'].transform(lambda x: x.fillna(x.mean()))
df['Attendance'].isnull().sum()

np.int64(0)

In [84]:
# interpolate(): fill gaps using linear (or other) interpolation - useful for ordered/time-series data
demo = pd.Series([3.0, np.nan, np.nan, 6.0, 7.0]) 
print(demo.interpolate())

0    3.0
1    4.0
2    5.0
3    6.0
4    7.0
dtype: float64

# Section 11: Duplicate Data

In [85]:
df.duplicated().sum()	# total number of duplicate rows (keeps first occurrence as non-duplicate)

np.int64(3)

In [86]:
df.duplicated(subset=['Age', 'Gender']).sum()	# duplicates based on a SUBSET of columns

np.int64(187)

In [89]:
print("Before:", df.shape) 
df_clean = df.drop_duplicates()
print("After drop_duplicates():", df_clean.shape)

Before: (203, 10)
After drop_duplicates(): (200, 10)

In [90]:
# keep='last' keeps the LAST occurrence instead of the first 
df.drop_duplicates(keep='last').shape

(200, 10)

#  Section 12: String Operations ( . str	accessor)

In [91]:
df['Gender'].str.lower().head()

0      male
1    female
2      male
3      male
4    female
Name: Gender, dtype: object

In [100]:
import pandas as pd

# strip() removes leading/trailing whitespace

messy = pd.Series([' Male', 'Female', ' Male '])

print(messy.str.strip())

0      Male
1    Female
2      Male
dtype: object

In [101]:
df['Gender'].str.replace('Male', 'M', regex=False).head()

0         M
1    Female
2         M
3         M
4    Female
Name: Gender, dtype: object

In [103]:
# Split() - break a string column into parts
names = pd.Series(['Anjali Chopade', 'Shravani Kamble', 'Pratiksha Khot']) 
names.str.split(' ')

0     [Anjali, Chopade]
1    [Shravani, Kamble]
2     [Pratiksha, Khot]
dtype: object

In [104]:
	names.str.split(' ', expand=True)	# expand=True returns a DataFrame of split parts

           0        1
0     Anjali  Chopade
1   Shravani   Kamble
2  Pratiksha     Khot

In [106]:
# contains() - boolean mask for substring matching (supports regex) 
df[df['Gender'].str.contains('Fem')].head(3)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
1,2,20,Female,89,84,46,67.3,1.8,No,Pass
4,5,19,Female,50,98,48,74.9,3.1,No,Pass
7,8,21,Female,53,51,71,76.3,1.1,Yes,Pass

In [108]:
# extract() - pull out a pattern using a regex capture group 
codes = pd.Series(['ID-001', 'ID-002', 'ID-103'])
codes.str.extract(r'ID-(\d+)')

     0
0  001
1  002
2  103

# Section 13: Date and Time

In [110]:
# tO_datetime() converts strings/objects into proper datetime64 dtype 
dates = pd.to_datetime(['2026-01-19', '2026-02-4', '2026-03-07'])
print(dates)
print(dates.dtype)

DatetimeIndex(['2026-01-19', '2026-02-04', '2026-03-07'], dtype='datetime64[ns]', freq=None)
datetime64[ns]

In [113]:
# Attach a synthetic 'AdmissionDate' column
rng = np.random.default_rng(7)

df['AdmissionDate'] = (
    pd.to_datetime('2026-01-06') +
    pd.to_timedelta(rng.integers(0, 100, len(df)), unit='D')
)

# Display the first 5 rows
print(df[['Student_ID', 'Age', 'AdmissionDate']].head())

   Student_ID  Age AdmissionDate
0           1   23    2026-04-10
1           2   20    2026-03-09
2           3   21    2026-03-15
3           4   23    2026-04-05
4           5   19    2026-03-04

In [130]:
# Extract month and day from Admission Date

df['AdmitMonth'] = df['AdmissionDate'].dt.month
df['AdmitDay'] = df['AdmissionDate'].dt.day_name()

print(df[['AdmissionDate', 'AdmitMonth', 'AdmitDay']].head())

  AdmissionDate  AdmitMonth   AdmitDay
0    2026-04-10           4     Friday
1    2026-03-09           3     Monday
2    2026-03-15           3     Sunday
3    2026-04-05           4     Sunday
4    2026-03-04           3  Wednesday

In [131]:
# date_range() - generate a sequence of dates 
pd.date_range(start='2026-01-06', periods=8, freq='D')

DatetimeIndex(['2026-01-06', '2026-01-07', '2026-01-08', '2026-01-09',
               '2026-01-10', '2026-01-11', '2026-01-12', '2026-01-13'],
              dtype='datetime64[ns]', freq='D')

In [134]:
pd.date_range(start='2026-01-10', periods=5, freq='ME')	# month-end frequency

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31'],
              dtype='datetime64[ns]', freq='ME')

In [137]:
rng = np.random.default_rng(7)

df['AdmitDate'] = (
    pd.to_datetime('2026-01-06') +
    pd.to_timedelta(rng.integers(0, 100, len(df)), unit='D')
)

print(df[['AdmitDate']].head())

   AdmitDate
0 2026-04-10
1 2026-03-09
2 2026-03-15
3 2026-04-05
4 2026-03-04

# Section 14: GroupBy — Split, Apply, Combine

In [143]:
# Split + apply (mean) + combine, in one line 
df.groupby('Gender')['Age'].mean()

Gender
Female    20.468085
Male      20.623853
Name: Age, dtype: float64

In [145]:
	# size() - count of rows per group (includes NaN counts unlike count())
df.groupby('Gender').size()

Gender
Female     94
Male      109
dtype: int64

In [146]:
	# get_group() - pull out a single group as its own DataFrame
df.groupby('Gender').get_group('Female').head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result,AdmissionDate,AdmitMonth,AdmitDay,AdmitDate
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,2026-03-09,3,Monday,2026-03-09
4,5,19,Female,50,98,48,74.9,3.1,No,Pass,2026-03-04,3,Wednesday,2026-03-04
7,8,21,Female,53,51,71,76.3,1.1,Yes,Pass,2026-01-28,1,Wednesday,2026-01-28
12,13,19,Female,89,69,84,61.1,2.5,Yes,Pass,2026-04-07,4,Tuesday,2026-04-07
13,14,19,Female,96,40,44,68.9,7.6,No,Pass,2026-01-06,1,Tuesday,2026-01-06

In [147]:
		# agg() - apply multiple aggregation functions at once 
df.groupby('Gender')['Age'].agg(['mean', 'min', 'max', 'count'])

             mean  min  max  count
Gender
Female  20.468085   17   24     94
Male    20.623853   17   24    109

In [150]:
# agg() with different functions per column df.groupby('Gender').agg({
summary = df.groupby('Gender').agg({
    'Age': 'mean',
    'Maths': ['mean', 'max'],
    'Result': lambda x: (x == 'Pass').sum()
})

print(summary)

              Age      Maths        Result
             mean       mean  max <lambda>
Gender
Female  20.468085  66.031915   99       82
Male    20.623853  66.862385  100       95

In [155]:
# transform() - returns an output the SAME SHAPE as the input (broadcast back to every row)
df['Age']	
df.groupby('Gender')['Age'].transform('mean') 
df[['Gender', 'Age', 'Age']].head()

   Gender  Age  Age
0    Male   23   23
1  Female   20   20
2    Male   21   21
3    Male   23   23
4  Female   19   19

In [157]:
# filter() - keep only groups that satisfy a condition 
df.groupby('Gender').filter(lambda g: g['Age'].mean() > 4).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result,AdmissionDate,AdmitMonth,AdmitDay,AdmitDate
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail,2026-04-10,4,Friday,2026-04-10
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,2026-03-09,3,Monday,2026-03-09
2,3,21,Male,74,62,81,94.5,3.5,No,Fail,2026-03-15,3,Sunday,2026-03-15
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass,2026-04-05,4,Sunday,2026-04-05
4,5,19,Female,50,98,48,74.9,3.1,No,Pass,2026-03-04,3,Wednesday,2026-03-04

# Section 15: Aggregation Functions

In [169]:
print("mean: Not Applicable")
print("median: Not Applicable")
print("mode:\n", df['Gender'].mode())

mean: Not Applicable
median: Not Applicable
mode:
 0    Male
Name: Gender, dtype: object

In [171]:
print(df.columns)

Index(['Student_ID', 'Gender', 'Maths', 'Science', 'English', 'Attendance',
       'Study_Hours', 'Sports', 'Result', 'AdmissionDate', 'AdmitMonth',
       'AdmitDay', 'AdmitDate'],
      dtype='object')

In [172]:
print("std:", df['Maths'].std())
print("var:", df['Maths'].var())
print("count:", df['Maths'].count())
print("nunique:", df['Gender'].nunique())

std: 19.036006820622315
var: 362.3695556747793
count: 203
nunique: 2

In [173]:
print("min:", df['Gender'].min())
print("max:", df['Gender'].max())

min: Female
max: Male

In [174]:
df['Science'].nlargest()	# top 5 values by default

16     100
66     100
89     100
185    100
191    100
Name: Science, dtype: int64

In [175]:
df['Maths'].nsmallest(3) # smallest 3 values

17    35
19    35
22    35
Name: Maths, dtype: int64

In [176]:
df['Maths'].product()	# product of all values (can underflow/overflow for many values - use cautiously)

np.int64(0)

In [177]:
# Value_counts() - frequency count per category (closely related to	aggregation)
df['Gender'].value_counts()

Gender
Male      109
Female     94
Name: count, dtype: int64

In [178]:
df['Gender'].value_counts(normalize=True)	# as proportions instead of raw [un]:	counts

Gender
Male      0.536946
Female    0.463054
Name: proportion, dtype: float64

In [179]:
 # Combine several aggregations into a single summary table for the whole 	DataFrame
df.select_dtypes(include=np.number).agg(['mean', 'std', 'min', 'max']).T

                  mean        std   min    max
Student_ID   99.251232  58.356373   1.0  200.0
Maths        66.477833  19.036007  35.0  100.0
Science      67.339901  20.107575  35.0  100.0
English      67.251232  18.816228  35.0  100.0
Attendance   79.928079  11.853138  60.4   99.9
Study_Hours   4.621608   2.086921   1.0    8.0
AdmitMonth    2.399015   1.030908   1.0    4.0