# Name: Anjali Suresh Chopade
# Roll_no.: 2013

# 📘 **NumPy Example**

## 1. The ndarray and why NumPy is memory-efficint

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]

## 2. Creating arrays (array , arange, linspace, zeros, ones, random.randint )

In [57]:
# 1. array() : Creates a array fro a list or tuple. 
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

# 2. arange(): Creates an array with values in a given range.
b = np.arange(1,11)
print(b)

# 3. linspace():Creates equally spaced values between two numbers.
c = np.linspace(2,20,5)
print(c)

# 4. zeros():  Creates an array filled with zeros.
d = np.zeros(10)
print(d)

# 5. ones():   Creates an array filled with ones.
e = np.ones(5)
print(e)

# 6. random.randint(): Creates an array of random integers. 
a = np.random.randint(1, 10, 5)
print(a)

[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2.   6.5 11.  15.5 20. ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[2 2 1 6 1]

### 3. Array attributes ( ndim, shape, size, dtype, itemsize )

In [59]:
# 1. ndim: Returns the number of dimensions of an array.
import numpy as np

a = np.array([[1,2],[3,4]])
print(a.ndim)

# 2. shape: Returns the shape (rows and columns) of an array.
a = np.array([[10, 20], [30, 40]])
print(a.shape)

# 3. size: Returns the total number of elements in an array.
a = np.array([10, 20,30, 40])
print(a.size)

# 4. dtype: Returns the data type of the array elements.
a = np.array([11,22,33,44,55])
print(a.dtype)

# 5. itemsize: Returns the size of each element in bytes.
a = np.array([120,130,140,150,160,170])
print(a.itemsize)

2
(2, 2)
4
int64
8

## 4. Indexing - Single Value

In [60]:
# 1D array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[2])

# 2D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1, 2])

# Negtive indexing 

arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])

# 3D Array
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr[1, 0, 1])

30
60
50
6

## 5. Slicing - Multiple values

In [61]:
import numpy as np

arr = np.array(['Banana', 'Apple', 'Mango', 'Orange'])

# index 1 to 2 (stop not included)
print(arr[1:3])

# start to index 1
print(arr[:2])

# index 2 to end
print(arr[2:])

# every second element (step = 2)
print(arr[::2])

# negative slicing (from end side)
print(arr[-3:-1])

['Apple' 'Mango']
['Banana' 'Apple']
['Mango' 'Orange']
['Banana' 'Mango']
['Apple' 'Mango']

## 6. Fancy indexing

In [62]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# selecting elements at index 0, 2, and 4
print(arr[[0, 2, 4]])

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# selecting row 0 and row 2
print(arr[[0, 2]])

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# selecting row 0 and row 2
print(arr[[0, 2]])

import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# selecting row 0 and row 2
print(arr[[0, 2]])

# selecting (0,1)=20 and (1,2)=60
print(arr[[0, 1], [1, 2]])

[10 30 50]
[[10 20 30]
 [70 80 90]]
[[10 20 30]
 [70 80 90]]
[[10 20 30]
 [70 80 90]]
[20 60]

## 7. Boolean (Mask) Indexing / filtering

In [63]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# selecting values greater than 30
print(arr[arr > 30])

arr > 30

# creating a boolean condition (mask)
mask = arr > 30

# applying mask to filter values
print(arr[mask])

# selecting values greater than 20 and less than 60
print(arr[(arr > 20) & (arr < 60)])

[40 50 60]
[40 50 60]
[30 40 50]

## 8. Mutabiliti - Replace,Append,Delete

In [64]:
# replace() - replace the value
import numpy as np

arr = np.array([10, 20, 30, 40])

# replacing value at index 1
arr[1] = 99

print(arr)

arr[1] = 99

# append() - add the new element at the end
import numpy as np

arr = np.array([10, 20, 30])

# adding new element at end
arr = np.append(arr, 40)

print(arr)

# delete() - delete the element
import numpy as np

arr = np.array([10, 20, 30, 40])

# deleting element at index 2
arr = np.delete(arr, 2)

print(arr)

[10 99 30 40]
[10 20 30 40]
[10 20 40]

## 9. Sorting

In [66]:
import numpy as np

arr = np.array([40, 10, 30, 20, 50])

# sorting in ascending order
print(np.sort(arr))

np.sort(arr)

# sorting in descending order
print(np.sort(arr)[::-1])

# sorting column-wise (axis = 0)
print(np.sort(arr, axis=0))

[10 20 30 40 50]
[50 40 30 20 10]
[10 20 30 40 50]

## 10. Copy vs Reference in NumPy (.copy)

In [67]:
# 1. Reference (No .copy())
import numpy as np

arr1 = np.array([10, 20, 30, 40])

# creating reference (same memory location)
arr2 = arr1

# modifying arr2
arr2[0] = 99

print("arr1:", arr1)
print("arr2:", arr2)

# True Copy (.copy())
arr1 = np.array([10, 20, 30, 40])

# creating an independent copy
arr2 = arr1.copy()

# modifying arr2
arr2[0] = 99

print("arr1:", arr1)
print("arr2:", arr2)

arr1: [99 20 30 40]
arr2: [99 20 30 40]
arr1: [10 20 30 40]
arr2: [99 20 30 40]

## 11. Rounding (np.around)

In [68]:
import numpy as np

arr = np.array([1.234, 2.567, 3.891])

# rounding to nearest integer
print(np.around(arr))

np.around(arr)

# rounding to 2 decimal places
print(np.around(arr, 2))

np.around(arr, 2)
print(np.around(arr, 1))

[1. 3. 4.]
[1.23 2.57 3.89]
[1.2 2.6 3.9]

## 12. Transpose

In [69]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# transpose of array
print(arr.T)
print(np.transpose(arr))

np.transpose(arr)
arr.T

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

## 13. Aggregation (np.sum and friends)

In [70]:
# sum (np.sum)
import numpy as np

arr = np.array([10, 20, 30, 40])

# sum of all elements
print(np.sum(arr))

np.sum(arr)

# mean: average of elements
print(np.mean(arr))

# Max: maximum value
print(np.max(arr))

# min : minimum value
print(np.min(arr))

 # Standard Deviation: spread of data
print(np.std(arr))

100
25.0
40
10
11.180339887498949

## 14. Reshaping, Flatten vs Ravel

In [71]:
# Reshaping (reshape): Changes the shape of the array (data size remains same)
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# reshaping into 2 rows and 3 columns
new_arr = arr.reshape(2, 3)

print(new_arr)

# Flatten: Converts array into 1D array (copy)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()

print(flat)

# Ravel: Converts array into 1D array (view)
rav = arr.ravel()

print(rav)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]

## BoradCasting

In [72]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# scalar 5 is broadcasted to all elements
print(arr + 5)

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)

a = np.array([[1],
              [2],
              [3]])

b = np.array([10, 20, 30])

print(a + b)

[6 7 8 9]
[[11 22 33]
 [14 25 36]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]

## 16. Vectorization

In [74]:
import numpy as np

arr = np.array([1, 2, 3, 4])

result = []

# using loop (slow method)
for i in arr:
    result.append(i * 2)

print(result)

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# vectorized addition
print(a + b)

arr = np.array([10, 15, 20, 25, 30])

# vectorized filtering
print(arr[arr > 20])

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]
[11 22 33]
[25 30]

## 17. Universal Functions(ufuncs)

In [76]:
for i in range(len(a)):
    c[i] = a[i] + b[i]

In [76]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print(np.add(a, b))      # [5 7 9]

# Subtraction
print(np.subtract(a, b)) # [-3 -3 -3]

# Multiplication
print(np.multiply(a, b)) # [4 10 18]

# Division
print(np.divide(a, b))   # [0.25 0.4 0.5]

for i in range(len(a)):
    c[i] = a[i] + b[i]

print(np.power(a, 2))   # square each element → [1 4 9]
print(np.mod(b, a))     # remainder → [0 1 0]

a = np.array([10, 20, 30])
b = np.array([15, 20, 25])

print(np.greater(a, b))   # [False False  True]
print(np.equal(a, b))     # [False  True False]

angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))  # sine values
print(np.cos(angles))  # cosine values

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[0 1 0]
[False False  True]
[False  True False]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]

## 18. Axis parameter explained visually

In [79]:
np.sum(a, axis=0)

np.int64(60)

In [84]:
np.sum(a, axis=1)

array([ 6, 15])

## 19. Stacking and Splitting

In [80]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays vertically
result = np.vstack((a, b))

print(result)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack arrays horizontally
result = np.hstack((a, b))

print(result)

a = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
result = np.split(a, 3)

print(result)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]

## 20. Linear Algebra with Numpy

In [88]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication
result = np.dot(A, B)

print(result)

A = np.array([[1, 2],
              [3, 4]])

# Transpose
print(A.T)

[[19 22]
 [43 50]]

In [81]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

# Transpose
print(A.T)

A = np.array([[1, 2],
              [3, 4]])

# Determinant
print(np.linalg.det(A))


A = np.array([[1, 2],
              [3, 4]])

# Inverse
print(np.linalg.inv(A))

[[1 3]
 [2 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]

## 21. Statistics with Numpy

In [82]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Calculate mean
print(np.mean(arr))

arr = np.array([10, 20, 30, 40, 50])

# Calculate median
print(np.median(arr))


arr = np.array([10, 20, 30, 40, 50])

# Standard deviation
print(np.std(arr))

arr = np.array([10, 20, 30, 40, 50])

# Variance
print(np.var(arr))

30.0
30.0
14.142135623730951
200.0

## 22. Matrix Operations

In [84]:
# Matrix addition
print(A + B)

# Matrix subtraction
print(A - B)


# Element-wise multiplication
print(A * B)

# OR
print(np.multiply(A, B))

# Matrix multiplication
print(A @ B)

# Matrix transpose
print(A.T)

# Square of matrix
print(np.linalg.matrix_power(A, 2))

# Matrix inverse
print(np.linalg.inv(A))

arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2x3 matrix
print(arr.reshape(2, 3))

# Shape
print(A.shape)

[[2 3]
 [4 4]]
[[0 1]
 [2 4]]
[[1 2]
 [3 0]]
[[1 2]
 [3 0]]
[[3 1]
 [7 3]]
[[1 3]
 [2 4]]
[[ 7 10]
 [15 22]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 2 3]
 [4 5 6]]
(2, 2)

## 23. One-Page Cheat Sheet

In [88]:
np.array([1,2,3])
np.zeros((2,3))
np.ones((2,3))
np.eye(3)
np.arange(0,10,2)
np.linspace(0,1,5)
np.random.rand(2,3)
np.random.randint(1,10,(2,2))

array([[9, 9],
       [9, 1]], dtype=int32)

In [86]:
arr.ndim        # Number of dimensions
arr.shape       # Shape
arr.size        # Total elements
arr.dtype       # Data type
arr.itemsize    # Size of one element (bytes)

8

In [87]:
arr[0]
arr[-1]
arr[1:5]
arr[:1]
arr[1:]
arr[0:2:1]
arr[arr>5]
arr[[0,2,4]]
arr.reshape(2,3)
arr.flatten()
arr.ravel()

array([1, 2, 3, 4, 5, 6])

# 📘 Pandas Example

# Section 1: Conceptual Foundations

In [3]:
import numpy as np
import pandas as pd

print("Pandas version:", pd.__version__) 
print("NumPy version:", np.__version__)

Pandas version: 2.3.1
NumPy version: 2.4.6

In [4]:
# QUick illustration: same data, four containers 
data = ['Banana', 5, 4.3]

py_list = data
py_dict = {'item': 'banana', 'count': 5, 'price': 4.3}
np_arr = np.array(data, dtype=object)
pd_series = pd.Series(data, index=['item', 'count', 'price'])

print("List:", py_list) 
print("Dict:", py_dict) 
print("NumPy array:", np_arr)
print("\nPandas Series (labeled, mixed types):") 
print(pd_series)

List: ['Banana', 5, 4.3]
Dict: {'item': 'banana', 'count': 5, 'price': 4.3}
NumPy array: ['Banana' 5 4.3]

Pandas Series (labeled, mixed types):
item     Banana
count         5
price       4.3
dtype: object

# Section 2: Pandas Series

In [5]:
# Create a Series from a list (default integer index)
lst = ['Banana', 5]
s = pd.Series(lst)
print(s)
print(type(s))

0    Banana
1         5
dtype: object
<class 'pandas.core.series.Series'>

In [6]:
# Create a Series with a custom index 
lst = ['Banana', 5]
s = pd.Series(lst, index=['a', 'c']) 
print(s)

a    Banana
c         5
dtype: object

In [7]:
# Create a Series with a custom index
lst = ['Banana', 5]
s = pd.Series(lst, index=['a', 'c']) 
print(s)

a    Banana
c         5
dtype: object

In [8]:
# Create a Series from a NumPy array
a = np.array(['Apple', 50])
print(a, type(a))

s = pd.Series(a, index=['a', 'b'])
print(s)

['Apple' '50'] <class 'numpy.ndarray'>
a    Apple
b       50
dtype: object

In [9]:
# Create a Series from a dictionary -> keys become the index 
d = {'a': [10, 20, 30], 'b': [30, 20, 10]}
s = pd.Series(d)
print(s)

a    [10, 20, 30]
b    [30, 20, 10]
dtype: object

In [10]:
# Indexing into a Series
s = pd.Series([1, 2, 3, 4],
index=['a', 'n', 's', 'h'])
print("By label:", s['a'])
print("By position:", s.iloc[1])
print("Slice by label:\n", s['n':'h'])	# label slicing is INCLUSIVE print(“Slice by position:\n”, s.iloc[1:3])
# positional slicing is EXCLUSIVE of end

By label: 1
By position: 2
Slice by label:
 n    2
s    3
h    4
dtype: int64

# Section 3: DataFrame Creation

In [11]:
# Create DataFrame from a dictionary 
s = {'coll': [10, 20]}
df_dict = pd.DataFrame(s)
print(df_dict)
print(type(df_dict)) 
print("Shape:", df_dict.shape)

   coll
0    10
1    20
<class 'pandas.core.frame.DataFrame'>
Shape: (2, 1)

In [12]:
# Create DataFrame from a dictionary
s = {'coll': [11, 22]}
df_dict = pd.DataFrame(s) 
print(df_dict) 
print(type(df_dict))
print("Shape:", df_dict.shape)

   coll
0    11
1    22
<class 'pandas.core.frame.DataFrame'>
Shape: (2, 1)

In [13]:
# Create DataFrame from a dictionary of equal-length lists (most common pattern)
df_multi = pd.DataFrame({
'name': ['Alisha', 'Rohan', 'Mahi'],
'age'  : [20, 21, 11],
'score' : [8.5, 2.0, 7.3]})
df_multi

     name  age  score
0  Alisha   20    8.5
1   Rohan   21    2.0
2    Mahi   11    7.3

# Section 4: Combining DataFrames

In [14]:
temp_df = pd.DataFrame({
    'city': ['Pune', 'Nagpur', 'Nashik', 'Kolhapur'],
    'temp': [30, 38, 29, 31]
})

hum_df = pd.DataFrame({
    'city': ['Pune', 'Nagpur', 'Aurangabad', 'Solapur'],
    'humidity': [72, 58, 65, 60]
})

print(temp_df)
print()
print(hum_df)

       city  temp
0      Pune    30
1    Nagpur    38
2    Nashik    29
3  Kolhapur    31

         city  humidity
0        Pune        72
1      Nagpur        58
2  Aurangabad        65
3     Solapur        60

In [15]:
# concat: stacks rows on top of each other (note duplicate index unless ignore_index=True)
pd.concat([temp_df, hum_df],
ignore_index=True)

         city  temp  humidity
0        Pune  30.0       NaN
1      Nagpur  38.0       NaN
2      Nashik  29.0       NaN
3    Kolhapur  31.0       NaN
4        Pune   NaN      72.0
5      Nagpur   NaN      58.0
6  Aurangabad   NaN      65.0
7     Solapur   NaN      60.0

In [16]:
# concat along columns (axis=1) - aligns by index position
pd.concat([temp_df, hum_df], axis=1)

       city  temp        city  humidity
0      Pune    30        Pune        72
1    Nagpur    38      Nagpur        58
2    Nashik    29  Aurangabad        65
3  Kolhapur    31     Solapur        60

In [17]:
# merge: outer join keeps ALL keys from both sides, filling NaN where unmatched
pd.merge(temp_df, hum_df, on='city', how='outer')

         city  temp  humidity
0  Aurangabad   NaN      65.0
1    Kolhapur  31.0       NaN
2      Nagpur  38.0      58.0
3      Nashik  29.0       NaN
4        Pune  30.0      72.0
5     Solapur   NaN      60.0

In [18]:
# merge: inner join keeps ONLY keys present in both DataFrames 
pd.merge(temp_df, hum_df, on='city', how='inner')

     city  temp  humidity
0    Pune    30        72
1  Nagpur    38        58

In [19]:
# merge: left / right joins
print(pd.merge(temp_df, hum_df, on='city', how='left')) 
print()
print(pd.merge(temp_df, hum_df, on='city', how='right'))

       city  temp  humidity
0      Pune    30      72.0
1    Nagpur    38      58.0
2    Nashik    29       NaN
3  Kolhapur    31       NaN

         city  temp  humidity
0        Pune  30.0        72
1      Nagpur  38.0        58
2  Aurangabad   NaN        65
3     Solapur   NaN        60

In [20]:
# join: merges on the INDEX instead of a column
left = temp_df.set_index('city') 
right = hum_df.set_index('city') 
left.join(right, how='outer')

            temp  humidity
city
Aurangabad   NaN      65.0
Kolhapur    31.0       NaN
Nagpur      38.0      58.0
Nashik      29.0       NaN
Pune        30.0      72.0
Solapur      NaN      60.0

# Section 5: Importing / Exporting Data

In [21]:
# --- Build a synthetic student dataset ---

np.random.seed(42)
n = 200

df = pd.DataFrame({
    'Student_ID': np.arange(1, n + 1),
    'Age': np.random.randint(17, 25, n),
    'Gender': np.random.choice(['Male', 'Female'], n, p=[0.55, 0.45]),
    'Maths': np.random.randint(35, 101, n),
    'Science': np.random.randint(35, 101, n),
    'English': np.random.randint(35, 101, n),
    'Attendance': np.round(np.random.uniform(60, 100, n), 1),
    'Study_Hours': np.round(np.random.uniform(1, 8, n), 1),
    'Sports': np.random.choice(['Yes', 'No'], n, p=[0.4, 0.6]),
    'Result': np.random.choice(['Pass', 'Fail'], n, p=[0.85, 0.15])
})

# Inject a few missing values and duplicate rows
df.loc[[5, 18, 50, 95], 'Study_Hours'] = np.nan
df = pd.concat([df, df.iloc[[10, 10, 25]]], ignore_index=True)

print(df.shape)
print(df.head())

(203, 10)
   Student_ID  Age  Gender  Maths  Science  English  Attendance  Study_Hours  \
0           1   23    Male     81       94       54        66.2          2.7
1           2   20  Female     89       84       46        67.3          1.8
2           3   21    Male     74       62       81        94.5          3.5
3           4   23    Male     86       75       35        97.8          3.0
4           5   19  Female     50       98       48        74.9          3.1

  Sports Result
0    Yes   Fail
1     No   Pass
2     No   Fail
3    Yes   Pass
4     No   Pass

In [22]:
# Export to CSV / Excel / JSON

df.to_csv('student_data.csv', index=False)
df.to_excel('student_data.xlsx', index=False)
df.to_json('student_data.json', orient='records')

print("Files written: student_data.csv / .xlsx / .json")

# Read them back

df_csv = pd.read_csv('student_data.csv')
df_xlsx = pd.read_excel('student_data.xlsx')
df_json = pd.read_json('student_data.json')

print(df_csv.shape, df_xlsx.shape, df_json.shape)

df_csv.head(3)

Files written: student_data.csv / .xlsx / .json
(203, 10) (203, 10) (203, 10)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
1,2,20,Female,89,84,46,67.3,1.8,No,Pass
2,3,21,Male,74,62,81,94.5,3.5,No,Fail

# Section 6: DataFrame Attributes

In [23]:
print("shape:", df.shape)
print("size:", df.size)
print("ndim:", df.ndim)
print(df)

shape: (203, 10)
size: 2030
ndim: 2
     Student_ID  Age  Gender  Maths  Science  English  Attendance  \
0             1   23    Male     81       94       54        66.2
1             2   20  Female     89       84       46        67.3
2             3   21    Male     74       62       81        94.5
3             4   23    Male     86       75       35        97.8
4             5   19  Female     50       98       48        74.9
..          ...  ...     ...    ...      ...      ...         ...
198         199   21  Female     42       60       72        76.9
199         200   19    Male     92       53       85        89.5
200          11   19    Male     53       47       67        88.6
201          11   19    Male     53       47       67        88.6
202          26   22    Male     98       45       43        94.2

     Study_Hours Sports Result
0            2.7    Yes   Fail
1            1.8     No   Pass
2            3.5     No   Fail
3            3.0    Yes   Pass
4            3.1     No   Pass
..           ...    ...    ...
198          1.1     No   Fail
199          1.5    Yes   Fail
200          3.7    Yes   Pass
201          3.7    Yes   Pass
202          5.5    Yes   Pass

[203 rows x 10 columns]

In [24]:
print("columns:", list(df.columns))
print("index:", df.index)

columns: ['Student_ID', 'Age', 'Gender', 'Maths', 'Science', 'English', 'Attendance', 'Study_Hours', 'Sports', 'Result']
index: RangeIndex(start=0, stop=203, step=1)

In [25]:
df.values[:5]	# underlying NumPy representation (loses column labels)

array([[1, 23, 'Male', 81, 94, 54, 66.2, 2.7, 'Yes', 'Fail'],
       [2, 20, 'Female', 89, 84, 46, 67.3, 1.8, 'No', 'Pass'],
       [3, 21, 'Male', 74, 62, 81, 94.5, 3.5, 'No', 'Fail'],
       [4, 23, 'Male', 86, 75, 35, 97.8, 3.0, 'Yes', 'Pass'],
       [5, 19, 'Female', 50, 98, 48, 74.9, 3.1, 'No', 'Pass']],
      dtype=object)

In [26]:
df.axes	# [row index, column index] as a list

[RangeIndex(start=0, stop=203, step=1),
 Index(['Student_ID', 'Age', 'Gender', 'Maths', 'Science', 'English',
        'Attendance', 'Study_Hours', 'Sports', 'Result'],
       dtype='object')]

In [27]:
df.keys()	# same as df.columns for a DataFrame

Index(['Student_ID', 'Age', 'Gender', 'Maths', 'Science', 'English',
       'Attendance', 'Study_Hours', 'Sports', 'Result'],
      dtype='object')

In [28]:
df.info()	# dtypes + non-null counts + memory usage - great first command on any new dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   203 non-null    int64
 1   Age          203 non-null    int32
 2   Gender       203 non-null    object
 3   Maths        203 non-null    int32
 4   Science      203 non-null    int32
 5   English      203 non-null    int32
 6   Attendance   203 non-null    float64
 7   Study_Hours  199 non-null    float64
 8   Sports       203 non-null    object
 9   Result       203 non-null    object
dtypes: float64(2), int32(4), int64(1), object(3)
memory usage: 12.8+ KB

In [29]:
df.describe()	# summary statistics for numeric columns (count, mean, std, min, quartiles, max)

,Student_ID,Age,Maths,Science,English,Attendance,Study_Hours
count,203.000000,203.000000,203.000000,203.000000,203.000000,203.000000,199.000000
mean,99.251232,20.551724,66.477833,67.339901,67.251232,79.928079,4.621608
std,58.356373,2.273618,19.036007,20.107575,18.816228,11.853138,2.086921
min,1.000000,17.000000,35.000000,35.000000,35.000000,60.400000,1.000000
25%,48.500000,19.000000,50.000000,51.000000,51.000000,69.600000,2.750000
50%,99.000000,20.000000,66.000000,67.000000,68.000000,80.800000,4.800000
75%,149.500000,23.000000,83.000000,85.000000,83.000000,90.000000,6.450000
max,200.000000,24.000000,100.000000,100.000000,100.000000,99.900000,8.000000

In [30]:
df.describe(include='object')	# summary stats for categorical/object columns

       Gender Sports Result
count     203    203    203
unique      2      2      2
top      Male     No   Pass
freq      109    122    177

# Section 7: Selecting & Indexing

In [31]:
	df.iloc[1]	# first row, by position

Student_ID          2
Age                20
Gender         Female
Maths              89
Science            84
English            46
Attendance       67.3
Study_Hours       1.8
Sports             No
Result           Pass
Name: 1, dtype: object

In [32]:
df.iloc[-1]

Student_ID       26
Age              22
Gender         Male
Maths            98
Science          45
English          43
Attendance     94.2
Study_Hours     5.5
Sports          Yes
Result         Pass
Name: 202, dtype: object

In [33]:
df.iloc[ [5, 8]]	# specific rows by position

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
8,9,23,Male,51,67,45,61.0,7.9,No,Pass

In [34]:
df.iloc[0:4, 0:1]	# rows 0-2, columns 0-1 (end exclusive, like Python slicing)

   Student_ID
0           1
1           2
2           3
3           4

In [35]:
df.loc[0]	# row with index label 0

Student_ID        1
Age              23
Gender         Male
Maths            81
Science          94
English          54
Attendance     66.2
Study_Hours     2.7
Sports          Yes
Result         Fail
Name: 0, dtype: object

In [36]:
df.iloc[[2, 6]]	# rows with index labels 2 and 3

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

In [37]:
df.iloc[:, 2]

0        Male
1      Female
2        Male
3        Male
4      Female
        ...
198    Female
199      Male
200      Male
201      Male
202      Male
Name: Gender, Length: 203, dtype: object

In [38]:
df.loc[[4, 8], 'Age':'Attendance']	# label-based slice (INCLUSIVE of 'TP')

   Age  Gender  Maths  Science  English  Attendance
4   19  Female     50       98       48        74.9
8   23    Male     51       67       45        61.0

In [39]:
df.loc[:, ['Maths', 'English']]	# multiple specific columns

     Maths  English
0       81       54
1       89       46
2       74       81
3       86       35
4       50       48
..     ...      ...
198     42       72
199     92       85
200     53       67
201     53       67
202     98       43

[203 rows x 2 columns]

In [40]:
# Boolean indexing
male_data = df[df['Gender'] == 'Male'] 
male_data.head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

In [41]:
# Multiple conditions: use & / I with parentheses (NOT 'and'/'or') 
df[(df['Age'] >= 7) & (df['Gender'] == 'Male')].tail()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
197,198,20,Male,70,39,100,76.7,4.2,No,Pass
199,200,19,Male,92,53,85,89.5,1.5,Yes,Fail
200,11,19,Male,53,47,67,88.6,3.7,Yes,Pass
201,11,19,Male,53,47,67,88.6,3.7,Yes,Pass
202,26,22,Male,98,45,43,94.2,5.5,Yes,Pass

In [42]:
# .query() - same filter, more readable for complex conditions 
df.query("Age >= 5 and Gender == 'Male'").head(5)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

In [43]:
# .query() - same filter, more readable for complex conditions 
df.query("Age >= 6 and Gender == 'Male'").head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail
2,3,21,Male,74,62,81,94.5,3.5,No,Fail
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail

# Section 8: Sorting, Ranking, Rename, Drop, Insert, Assign,Replace

In [44]:
# Sort by a single column 
df.sort_values(by='Attendance', ascending=False).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
188,189,23,Male,88,85,83,99.9,5.8,Yes,Pass
145,146,23,Female,38,98,81,99.5,4.2,Yes,Pass
66,67,20,Male,78,100,100,99.4,1.6,Yes,Pass
195,196,18,Male,62,79,35,99.4,6.6,No,Pass
157,158,18,Female,54,68,41,98.8,7.6,Yes,Fail

In [45]:
# Sort by multiple columns
df.sort_values(by=['Gender', 'Age'], ascending=[True, False]).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
14,15,24,Female,57,81,39,69.2,6.5,No,Pass
18,19,24,Female,92,90,36,92.0,NaN,Yes,Pass
46,47,24,Female,35,38,64,85.0,2.6,No,Fail
56,57,24,Female,67,84,73,95.8,7.0,No,Pass
83,84,24,Female,58,90,91,83.9,7.1,Yes,Pass

In [46]:
# rank() - assigns a rank to each value (useful for percentile/competition-style ranking)
df['Age_rank'] = df['Age'].rank(ascending=False) 
df[['Age', 'Age_rank']].head()

   Age  Age_rank
0   23      40.0
1   20     115.5
2   21      89.0
3   23      40.0
4   19     143.0

In [47]:
# Rename columns
df_renamed = df.rename(columns={'Maths':'M1','Science':'s1'})
df_renamed.head(2)

,Student_ID,Age,Gender,M1,s1,English,Attendance,Study_Hours,Sports,Result,Age_rank
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail,40.0
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,115.5

In [48]:
# Drop columns
# Drop one column
df.drop('Age_rank', axis=1, errors='ignore', inplace=True)

# Drop multiple columns
df.drop(['Maths', 'Science'], axis=1).head(2)

   Student_ID  Age  Gender  English  Attendance  Study_Hours Sports Result
0           1   23    Male       54        66.2          2.7    Yes   Fail
1           2   20  Female       46        67.3          1.8     No   Pass

In [49]:
# Drop rows
df.drop([0, 1, 2], axis=0).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass
4,5,19,Female,50,98,48,74.9,3.1,No,Pass
5,6,24,Male,47,61,98,70.8,NaN,No,Pass
6,7,21,Male,64,97,72,85.8,1.3,No,Fail
7,8,21,Female,53,51,71,76.3,1.1,Yes,Pass

In [51]:
# Insert a column at a specific position
df = pd.read_csv("student_data.csv")   # किंवा तुझ्या file चे नाव

df_copy = df.copy()

df_copy.insert(1, 'AgeGroup',
               np.where(df_copy['Age'] >= 60, 'Senior', 'Adult'))

df_copy.head(3)

,Student_ID,AgeGroup,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
0,1,Adult,23,Male,81,94,54,66.2,2.7,Yes,Fail
1,2,Adult,20,Female,89,84,46,67.3,1.8,No,Pass
2,3,Adult,21,Male,74,62,81,94.5,3.5,No,Fail

In [54]:
# assign() - create one or more new columns in a chainable/functional style 
df_assigned = df.assign(
TB_per_DB=lambda x: x['Maths'] / (x['Science'] + 0.02),	# +0.01 avoids divide-by-zero
IsMale=lambda x: x['Gender'] == 'Male' )
df_assigned.head(3)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result,TB_per_DB,IsMale
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail,0.861519,True
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,1.059272,False
2,3,21,Male,74,62,81,94.5,3.5,No,Fail,1.193163,True

In [57]:
# replace() - swap specific values
df['Gender'].replace({'Male': 'm', })

0           m
1      Female
2           m
3           m
4      Female
        ...
198    Female
199         m
200         m
201         m
202         m
Name: Gender, Length: 203, dtype: object

# Section 9: map, apply, DataFrame.map, and Lambda Functions

In [59]:
# map() on a Series with a dictionary 
gender_code = {'Male': 2, 'Female' : 1}
df['Gender_code'] = df['Gender'].map(gender_code) 
df[['Gender', 'Gender_code']].head()

   Gender  Gender_code
0    Male            2
1  Female            1
2    Male            2
3    Male            2
4  Female            1

In [60]:
# map() with a function / lambda
df['Age_in_months'] = df['Age'].map(lambda x: x * 14) 
df[['Age', 'Age_in_months']].head()

   Age  Age_in_months
0   23            322
1   20            280
2   21            294
3   23            322
4   19            266

In [62]:
# apply() on a Series - equivalent to map() for simple functions 
df['M1'] = df['Maths'].apply(lambda x: x ** 4)
df[['Maths', 'M1']].head()

   Maths        M1
0     81  43046721
1     89  62742241
2     74  29986576
3     86  54700816
4     50   6250000

In [65]:
# apply() on a DataFrame, row-wise (axis=1)

def student_risk(row):
    if row['Maths'] < 40 or row['Attendance'] < 75:
        return 'High'
    else:
        return 'Low'

df['Risk'] = df.apply(student_risk, axis=1)

df[['Maths', 'Attendance', 'Risk']].head()

   Maths  Attendance  Risk
0     81        66.2  High
1     89        67.3  High
2     74        94.5   Low
3     86        97.8   Low
4     50        74.9  High

In [66]:
# apply() on a DataFrame, column-wise (axis=0, the default) - function receives a full column
df[['Age', 'Maths', 'Science']].apply(lambda col: col.max() - col.min())

Age         7
Maths      65
Science    65
dtype: int64

In [68]:
# DataFrame.map() - element-wise transform across the WHOLE frame (numeric columns shown here)
df[['Age', 'Maths', 'Science']].map(lambda x: round(x, 1))

     Age  Maths  Science
0     23     81       94
1     20     89       84
2     21     74       62
3     23     86       75
4     19     50       98
..   ...    ...      ...
198   21     42       60
199   19     92       53
200   19     53       47
201   19     53       47
202   22     98       45

[203 rows x 3 columns]

In [70]:
# Cleanup helper columns
df.drop(columns=['Gender_code', 'Age_in_months', 'Risk'], inplace=True, errors='ignore')

print(df.head())

   Student_ID  Age  Gender  Maths  Science  English  Attendance  Study_Hours  \
0           1   23    Male     81       94       54        66.2          2.7
1           2   20  Female     89       84       46        67.3          1.8
2           3   21    Male     74       62       81        94.5          3.5
3           4   23    Male     86       75       35        97.8          3.0
4           5   19  Female     50       98       48        74.9          3.1

  Sports Result
0    Yes   Fail
1     No   Pass
2     No   Fail
3    Yes   Pass
4     No   Pass

# Section 10: Missing Values

In [71]:
df.isnull().sum()	# count of missing values per column

Student_ID     0
Age            0
Gender         0
Maths          0
Science        0
English        0
Attendance     0
Study_Hours    4
Sports         0
Result         0
dtype: int64

In [72]:
df.isna().sum()	# isna() is an alias for isnull() - identical behavior

Student_ID     0
Age            0
Gender         0
Maths          0
Science        0
English        0
Attendance     0
Study_Hours    4
Sports         0
Result         0
dtype: int64

In [73]:
df.notnull().sum() # inverse: count of N0N-missing values per column

Student_ID     203
Age            203
Gender         203
Maths          203
Science        203
English        203
Attendance     203
Study_Hours    199
Sports         203
Result         203
dtype: int64

In [76]:
# dropna(): remove rows with ANY missing value 
print("Before:", df.shape)
print("After dropna():", df.dropna().shape)

Before: (203, 10)
After dropna(): (199, 10)

In [78]:
df['Study_Hours'].fillna(1.0).isnull().sum()

np.int64(0)

In [81]:
# fillna() with the column mean / median (common imputation strategy) 
mean_fill = df['Attendance'].fillna(df['Attendance'].mean())
median_fill = df['Attendance'].fillna(df['Attendance'].median())
print("Mean used:", df['Attendance'].mean())
print("Median used:", df['Attendance'].median())

Mean used: 79.928078817734
Median used: 80.8

In [83]:
# fillna() with a GROUPED statistic - more accurate than a single global fill value
df['Attendance']	
df.groupby('Gender')['Attendance'].transform(lambda x: x.fillna(x.mean()))
df['Attendance'].isnull().sum()

np.int64(0)

In [84]:
# interpolate(): fill gaps using linear (or other) interpolation - useful for ordered/time-series data
demo = pd.Series([3.0, np.nan, np.nan, 6.0, 7.0]) 
print(demo.interpolate())

0    3.0
1    4.0
2    5.0
3    6.0
4    7.0
dtype: float64

# Section 11: Duplicate Data

In [85]:
df.duplicated().sum()	# total number of duplicate rows (keeps first occurrence as non-duplicate)

np.int64(3)

In [86]:
df.duplicated(subset=['Age', 'Gender']).sum()	# duplicates based on a SUBSET of columns

np.int64(187)

In [89]:
print("Before:", df.shape) 
df_clean = df.drop_duplicates()
print("After drop_duplicates():", df_clean.shape)

Before: (203, 10)
After drop_duplicates(): (200, 10)

In [90]:
# keep='last' keeps the LAST occurrence instead of the first 
df.drop_duplicates(keep='last').shape

(200, 10)

#  Section 12: String Operations ( . str	accessor)

In [91]:
df['Gender'].str.lower().head()

0      male
1    female
2      male
3      male
4    female
Name: Gender, dtype: object

In [100]:
import pandas as pd

# strip() removes leading/trailing whitespace

messy = pd.Series([' Male', 'Female', ' Male '])

print(messy.str.strip())

0      Male
1    Female
2      Male
dtype: object

In [101]:
df['Gender'].str.replace('Male', 'M', regex=False).head()

0         M
1    Female
2         M
3         M
4    Female
Name: Gender, dtype: object

In [103]:
# Split() - break a string column into parts
names = pd.Series(['Anjali Chopade', 'Shravani Kamble', 'Pratiksha Khot']) 
names.str.split(' ')

0     [Anjali, Chopade]
1    [Shravani, Kamble]
2     [Pratiksha, Khot]
dtype: object

In [104]:
	names.str.split(' ', expand=True)	# expand=True returns a DataFrame of split parts

           0        1
0     Anjali  Chopade
1   Shravani   Kamble
2  Pratiksha     Khot

In [106]:
# contains() - boolean mask for substring matching (supports regex) 
df[df['Gender'].str.contains('Fem')].head(3)

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result
1,2,20,Female,89,84,46,67.3,1.8,No,Pass
4,5,19,Female,50,98,48,74.9,3.1,No,Pass
7,8,21,Female,53,51,71,76.3,1.1,Yes,Pass

In [108]:
# extract() - pull out a pattern using a regex capture group 
codes = pd.Series(['ID-001', 'ID-002', 'ID-103'])
codes.str.extract(r'ID-(\d+)')

     0
0  001
1  002
2  103

# Section 13: Date and Time

In [110]:
# tO_datetime() converts strings/objects into proper datetime64 dtype 
dates = pd.to_datetime(['2026-01-19', '2026-02-4', '2026-03-07'])
print(dates)
print(dates.dtype)

DatetimeIndex(['2026-01-19', '2026-02-04', '2026-03-07'], dtype='datetime64[ns]', freq=None)
datetime64[ns]

In [113]:
# Attach a synthetic 'AdmissionDate' column
rng = np.random.default_rng(7)

df['AdmissionDate'] = (
    pd.to_datetime('2026-01-06') +
    pd.to_timedelta(rng.integers(0, 100, len(df)), unit='D')
)

# Display the first 5 rows
print(df[['Student_ID', 'Age', 'AdmissionDate']].head())

   Student_ID  Age AdmissionDate
0           1   23    2026-04-10
1           2   20    2026-03-09
2           3   21    2026-03-15
3           4   23    2026-04-05
4           5   19    2026-03-04

In [130]:
# Extract month and day from Admission Date

df['AdmitMonth'] = df['AdmissionDate'].dt.month
df['AdmitDay'] = df['AdmissionDate'].dt.day_name()

print(df[['AdmissionDate', 'AdmitMonth', 'AdmitDay']].head())

  AdmissionDate  AdmitMonth   AdmitDay
0    2026-04-10           4     Friday
1    2026-03-09           3     Monday
2    2026-03-15           3     Sunday
3    2026-04-05           4     Sunday
4    2026-03-04           3  Wednesday

In [131]:
# date_range() - generate a sequence of dates 
pd.date_range(start='2026-01-06', periods=8, freq='D')

DatetimeIndex(['2026-01-06', '2026-01-07', '2026-01-08', '2026-01-09',
               '2026-01-10', '2026-01-11', '2026-01-12', '2026-01-13'],
              dtype='datetime64[ns]', freq='D')

In [134]:
pd.date_range(start='2026-01-10', periods=5, freq='ME')	# month-end frequency

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31'],
              dtype='datetime64[ns]', freq='ME')

In [137]:
rng = np.random.default_rng(7)

df['AdmitDate'] = (
    pd.to_datetime('2026-01-06') +
    pd.to_timedelta(rng.integers(0, 100, len(df)), unit='D')
)

print(df[['AdmitDate']].head())

   AdmitDate
0 2026-04-10
1 2026-03-09
2 2026-03-15
3 2026-04-05
4 2026-03-04

# Section 14: GroupBy — Split, Apply, Combine

In [143]:
# Split + apply (mean) + combine, in one line 
df.groupby('Gender')['Age'].mean()

Gender
Female    20.468085
Male      20.623853
Name: Age, dtype: float64

In [145]:
	# size() - count of rows per group (includes NaN counts unlike count())
df.groupby('Gender').size()

Gender
Female     94
Male      109
dtype: int64

In [146]:
	# get_group() - pull out a single group as its own DataFrame
df.groupby('Gender').get_group('Female').head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result,AdmissionDate,AdmitMonth,AdmitDay,AdmitDate
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,2026-03-09,3,Monday,2026-03-09
4,5,19,Female,50,98,48,74.9,3.1,No,Pass,2026-03-04,3,Wednesday,2026-03-04
7,8,21,Female,53,51,71,76.3,1.1,Yes,Pass,2026-01-28,1,Wednesday,2026-01-28
12,13,19,Female,89,69,84,61.1,2.5,Yes,Pass,2026-04-07,4,Tuesday,2026-04-07
13,14,19,Female,96,40,44,68.9,7.6,No,Pass,2026-01-06,1,Tuesday,2026-01-06

In [147]:
		# agg() - apply multiple aggregation functions at once 
df.groupby('Gender')['Age'].agg(['mean', 'min', 'max', 'count'])

             mean  min  max  count
Gender
Female  20.468085   17   24     94
Male    20.623853   17   24    109

In [150]:
# agg() with different functions per column df.groupby('Gender').agg({
summary = df.groupby('Gender').agg({
    'Age': 'mean',
    'Maths': ['mean', 'max'],
    'Result': lambda x: (x == 'Pass').sum()
})

print(summary)

              Age      Maths        Result
             mean       mean  max <lambda>
Gender
Female  20.468085  66.031915   99       82
Male    20.623853  66.862385  100       95

In [155]:
# transform() - returns an output the SAME SHAPE as the input (broadcast back to every row)
df['Age']	
df.groupby('Gender')['Age'].transform('mean') 
df[['Gender', 'Age', 'Age']].head()

   Gender  Age  Age
0    Male   23   23
1  Female   20   20
2    Male   21   21
3    Male   23   23
4  Female   19   19

In [157]:
# filter() - keep only groups that satisfy a condition 
df.groupby('Gender').filter(lambda g: g['Age'].mean() > 4).head()

,Student_ID,Age,Gender,Maths,Science,English,Attendance,Study_Hours,Sports,Result,AdmissionDate,AdmitMonth,AdmitDay,AdmitDate
0,1,23,Male,81,94,54,66.2,2.7,Yes,Fail,2026-04-10,4,Friday,2026-04-10
1,2,20,Female,89,84,46,67.3,1.8,No,Pass,2026-03-09,3,Monday,2026-03-09
2,3,21,Male,74,62,81,94.5,3.5,No,Fail,2026-03-15,3,Sunday,2026-03-15
3,4,23,Male,86,75,35,97.8,3.0,Yes,Pass,2026-04-05,4,Sunday,2026-04-05
4,5,19,Female,50,98,48,74.9,3.1,No,Pass,2026-03-04,3,Wednesday,2026-03-04

# Section 15: Aggregation Functions

In [169]:
print("mean: Not Applicable")
print("median: Not Applicable")
print("mode:\n", df['Gender'].mode())

mean: Not Applicable
median: Not Applicable
mode:
 0    Male
Name: Gender, dtype: object

In [171]:
print(df.columns)

Index(['Student_ID', 'Gender', 'Maths', 'Science', 'English', 'Attendance',
       'Study_Hours', 'Sports', 'Result', 'AdmissionDate', 'AdmitMonth',
       'AdmitDay', 'AdmitDate'],
      dtype='object')

In [172]:
print("std:", df['Maths'].std())
print("var:", df['Maths'].var())
print("count:", df['Maths'].count())
print("nunique:", df['Gender'].nunique())

std: 19.036006820622315
var: 362.3695556747793
count: 203
nunique: 2

In [173]:
print("min:", df['Gender'].min())
print("max:", df['Gender'].max())

min: Female
max: Male

In [174]:
df['Science'].nlargest()	# top 5 values by default

16     100
66     100
89     100
185    100
191    100
Name: Science, dtype: int64

In [175]:
df['Maths'].nsmallest(3) # smallest 3 values

17    35
19    35
22    35
Name: Maths, dtype: int64

In [176]:
df['Maths'].product()	# product of all values (can underflow/overflow for many values - use cautiously)

np.int64(0)

In [177]:
# Value_counts() - frequency count per category (closely related to	aggregation)
df['Gender'].value_counts()

Gender
Male      109
Female     94
Name: count, dtype: int64

In [178]:
df['Gender'].value_counts(normalize=True)	# as proportions instead of raw [un]:	counts

Gender
Male      0.536946
Female    0.463054
Name: proportion, dtype: float64

In [179]:
 # Combine several aggregations into a single summary table for the whole 	DataFrame
df.select_dtypes(include=np.number).agg(['mean', 'std', 'min', 'max']).T

                  mean        std   min    max
Student_ID   99.251232  58.356373   1.0  200.0
Maths        66.477833  19.036007  35.0  100.0
Science      67.339901  20.107575  35.0  100.0
English      67.251232  18.816228  35.0  100.0
Attendance   79.928079  11.853138  60.4   99.9
Study_Hours   4.621608   2.086921   1.0    8.0
AdmitMonth    2.399015   1.030908   1.0    4.0

# 🎯 NumPy Practice - 50 Coding Questions (Easy --> Hard)

## 1. Create a 1-D array of numbers 1 to 20.

In [1]:
import numpy as np

# Create 1-D array from 1 to 20
arr = np.arange(1, 21)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

## 2.  Create a 5*5 aaray of all zeros.

In [3]:
import numpy as np

# Create 5x5 array of zeros
arr = np.zeros((5, 5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

## 3. Create a 4*4 identity matrix.

In [4]:
import numpy as np

# Create 4x4 identity matrix
arr = np.eye(4)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

## 4. Create an array of 10 evenly spaced numbers between O and 1.

In [5]:
import numpy as np

# Create 10 evenly spaced numbers between 0 and 1
arr = np.linspace(0, 1, 10)

print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

## 5. Reverse a given 1-D array.

In [6]:
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4, 5])

# Reverse the array
rev_arr = arr[::-1]

print("Original:", arr)
print("Reversed:", rev_arr)

Original: [1 2 3 4 5]
Reversed: [5 4 3 2 1]

## 6. Find the shape,size,and dtype of a given array.

In [7]:
import numpy as np

# Create sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Find properties
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64

## 7. Replace all odd numbers in an array with -1.

In [8]:
arr = np.arange(1, 11)
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]

## 8. Find the sum, mean, and max of an array.

In [9]:
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))

Sum: 15
Mean: 3.0
Max: 5

## 9.	Create a 3x3 array of random integers between 1 and 100.

In [10]:
arr = np.random.randint(1, 101, (3,3))
print(arr)

[[26 13  4]
 [66 72 68]
 [70 35 67]]

## 10.	Stack two 1-D arrays vertically and horizontally.

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

## 11. Extract every 3rd element from an array.

In [12]:
arr = np.arange(1, 16)
print(arr[::3])

[ 1  4  7 10 13]

## 12.	Find common elements between two arrays.

In [13]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])

print(np.intersect1d(a, b))

[3 4]

## 13.	Convert a list of temperatures in Celsius to Fahrenheit using vectorized math.

In [14]:
c = np.array([0, 20, 30, 40])
f = (c * 9/5) + 32
print(f)

[ 32.  68.  86. 104.]

## 14.	Count the number of even numbers in an array.

In [15]:
arr = np.array([1,2,3,4,5,6])
print(np.sum(arr % 2 == 0))

3

## 15.	Create an array and compute its transpose.

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]

## 16.	Normalize an array to the range [0, 1] using broadcasting.

In [17]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
norm = (arr - arr.min()) / (arr.max() - arr.min())

print(norm)

[0.   0.25 0.5  0.75 1.  ]

## 17.	Find the indices of all elements greater than the array's mean.

In [18]:
arr = np.array([1,2,3,4,5])
mean = np.mean(arr)

print(np.where(arr > mean))

(array([3, 4]),)

## 18.	Create a checkerboard pattern (8x8) of 0s and 1 s using slicing.

In [19]:
arr = np.zeros((8,8), dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

## 19.	Compute the row-wise and column-wise sum of a 2-D matrix.

In [20]:
arr = np.array([[1,2,3],[4,5,6]])

print("Row sum:", np.sum(arr, axis=1))
print("Column sum:", np.sum(arr, axis=0))

Row sum: [ 6 15]
Column sum: [5 7 9]

## 20.	Replace all NaN values in an array with the column mean.

In [21]:
arr = np.array([[1, np.nan], [3, 4]])

col_mean = np.nanmean(arr, axis=0)

inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])

print(arr)

[[1. 4.]
 [3. 4.]]

## 21.	Find the second-largest value in an array without sorting the whole array.

In [22]:
arr = np.array([10, 20, 4, 45, 99])

print(np.partition(arr, -2)[-2])

45

## 22.	Given two matrices, check if they can be multiplied, then multiply them.

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

if A.shape[1] == B.shape[0]:
    print(np.dot(A,B))
else:
    print("Cannot multiply")

[[19 22]
 [43 50]]

## 23.	Implement min-max scaling on a feature matrix (axis=0).

In [24]:
arr = np.array([[1,2],[3,4],[5,6]])

scaled = (arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))

print(scaled)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]

## 24.	Generate a random matrix and compute its inverse and determinant.

In [25]:
arr = np.random.randint(1,10,(3,3))

print("Matrix:\n", arr)
print("Determinant:", np.linalg.det(arr))
print("Inverse:\n", np.linalg.inv(arr))

Matrix:
 [[7 9 6]
 [4 1 6]
 [9 3 2]]
Determinant: 320.0000000000002
Inverse:
 [[-0.05      0.        0.15    ]
 [ 0.14375  -0.125    -0.05625 ]
 [ 0.009375  0.1875   -0.090625]]

## 25.	Given an array of exam scores, bucket them into grade categories using boolean masks (A/B/C/F).

In [26]:
scores = np.array([85, 72, 60, 40])

grades = np.empty(scores.shape, dtype=str)

grades[scores >= 80] = 'A'
grades[(scores >= 60) & (scores < 80)] = 'B'
grades[(scores >= 50) & (scores < 60)] = 'C'
grades[scores < 50] = 'F'

print(grades)

['A' 'B' 'B' 'F']

## 26.	Flatten a 3-D array and confirm whether the result is a view or copy.

In [27]:
arr = np.arange(8).reshape(2,2,2)

flat = arr.ravel()   # view
print(flat)

# Check
flat[0] = 100
print(arr)  # changes reflect → it's a view

[0 1 2 3 4 5 6 7]
[[[100   1]
  [  2   3]]

 [[  4   5]
  [  6   7]]]

## 27.	Compute the moving average of a 1-D array with a window size of 3.

In [28]:
arr = np.array([1,2,3,4,5])

ma = np.convolve(arr, np.ones(3)/3, mode='valid')

print(ma)

[2. 3. 4.]

## 28.	Implement one-hot encoding for an array of class labels using NumPy only.

In [29]:
import numpy as np

labels = np.array([0, 1, 2, 1])

one_hot = np.eye(np.max(labels)+1)[labels]

print(one_hot)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

## 29.	Given a confusion matrix, compute accuracy using only NumPy operations.

In [30]:
cm = np.array([[5, 2],
               [1, 7]])

accuracy = np.trace(cm) / np.sum(cm)

print("Accuracy:", accuracy)

Accuracy: 0.8

## 30.	Shuffle a feature matrix x and label vector y together using the same permutation.

In [31]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([0,1,0])

perm = np.random.permutation(len(x))

x_shuffled = x[perm]
y_shuffled = y[perm]

print(x_shuffled)
print(y_shuffled)

[[1 2]
 [3 4]
 [5 6]]
[0 1 0]

## 31.	Compute pairwise Euclidean distances between two sets of points (no loops).

In [32]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

dist = np.sqrt(((A[:, np.newaxis] - B)**2).sum(axis=2))

print(dist)

[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]

## 32.	Implement the sigmoid and ReLU functions and apply them to a random array.

In [33]:
arr = np.random.randn(5)

sigmoid = 1 / (1 + np.exp(-arr))
relu = np.maximum(0, arr)

print("Sigmoid:", sigmoid)
print("ReLU:", relu)

Sigmoid: [0.48407928 0.31489871 0.40584565 0.5688598  0.62998837]
ReLU: [0.         0.         0.         0.27720067 0.53216694]

## 33.	Split a dataset array into 80/20 train/test using slicing after shuffling.

In [34]:
data = np.arange(10)

np.random.shuffle(data)

split = int(0.8 * len(data))

train = data[:split]
test = data[split:]

print("Train:", train)
print("Test:", test)

Train: [3 7 6 5 8 4 9 1]
Test: [2 0]

## 34.	Given an array of RGB pixel values, convert it to grayscale using a weighted sum.

In [35]:
rgb = np.array([[255, 0, 0],
                [0, 255, 0],
                [0, 0, 255]])

gray = np.dot(rgb, [0.299, 0.587, 0.114])

print(gray)

[ 76.245 149.685  29.07 ]

## 35.	Find duplicate rows in a 2-D array.

In [36]:
arr = np.array([[1,2],
                [3,4],
                [1,2],
                [5,6]])

_, idx = np.unique(arr, axis=0, return_index=True)

duplicates = np.delete(arr, idx, axis=0)

print(duplicates)

[[1 2]]

## 36.	Implement a simple linear regression using the normal equation (no Scikit-learn).

In [37]:
import numpy as np

X = np.array([[1],[2],[3],[4]])
y = np.array([2,4,6,8])

X_b = np.c_[np.ones((len(X),1)), X]   # add bias
theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

print("Intercept & Slope:", theta)

Intercept & Slope: [0. 2.]

## 37.	Implement K-Means cluster assignment step (assign each point to its nearest centroid) using only broadcasting.

In [38]:
X = np.array([[1,2],[3,4],[5,6]])
centroids = np.array([[1,1],[5,5]])

dist = np.sqrt(((X[:, np.newaxis] - centroids)**2).sum(axis=2))
labels = np.argmin(dist, axis=1)

print(labels)

[0 1 1]

## 38.	Implement PCA from scratch using np.11na1g.e1g On the covariance matrix.

In [39]:
X = np.array([[1,2],[3,4],[5,6]])

X_mean = X - np.mean(X, axis=0)
cov = np.cov(X_mean, rowvar=False)

eig_val, eig_vec = np.linalg.eig(cov)

print("Eigenvalues:", eig_val)
print("Eigenvectors:\n", eig_vec)

Eigenvalues: [8. 0.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

## 39.	Implement a single forward pass of a 2-layer neural network using only NumPy (matrix multiply + sigmoid).

In [40]:
X = np.array([[1,2]])
W1 = np.random.rand(2,3)
W2 = np.random.rand(3,1)

def sigmoid(x):
    return 1/(1+np.exp(-x))

h = sigmoid(X @ W1)
output = sigmoid(h @ W2)

print(output)

[[0.80491483]]

## 40.	Implement softmax (numerically stable version, subtracting the max) for a batch of logits.

In [41]:
x = np.array([2.0, 1.0, 0.1])

e_x = np.exp(x - np.max(x))
softmax = e_x / e_x.sum()

print(softmax)

[0.65900114 0.24243297 0.09856589]

## 41.	Implement gradient descent to fit a line y = mx + b to noisy data.

In [42]:
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])

m, b = 0, 0
lr = 0.01

for _ in range(1000):
    y_pred = m*x + b
    dm = (-2/len(x)) * np.sum(x*(y - y_pred))
    db = (-2/len(x)) * np.sum(y - y_pred)
    
    m -= lr*dm
    b -= lr*db

print(m, b)

1.9896587550255742 0.030404521305361965

## 42.	Compute a sliding-window (convolution-style) sum over a 1-D signal without using np.convolve .

In [43]:
arr = np.array([1,2,3,4,5])
k = 3

result = np.array([arr[i:i+k].sum() for i in range(len(arr)-k+1)])

print(result)

[ 6  9 12]

## 43.	Implement batch normalization (subtract mean, divide by std, per feature) for a batch of data.

In [44]:
X = np.array([[1,2],[3,4],[5,6]])

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

norm = (X - mean) / std

print(norm)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]

## 44.	Given a dataset with outliers, implement an IQR-based outlier removal function using only boolean masking.

In [45]:
arr = np.array([10,12,14,100,18,20])

Q1 = np.percentile(arr, 25)
Q3 = np.percentile(arr, 75)
IQR = Q3 - Q1

filtered = arr[(arr >= Q1 - 1.5*IQR) & (arr <= Q3 + 1.5*IQR)]

print(filtered)

[10 12 14 18 20]

## 45.	Implement nearest-neighbor classification (1-NN) using only NumPy distance computations.

In [46]:
train_X = np.array([[1,2],[3,4],[5,6]])
train_y = np.array([0,1,1])

test = np.array([2,3])

dist = np.sqrt(((train_X - test)**2).sum(axis=1))
label = train_y[np.argmin(dist)]

print(label)

0

## 46.	Build a simple image-patch extractor: given an image array and patch size, extract all non-overlapping patches.

In [47]:
img = np.arange(16).reshape(4,4)
patch_size = 2

patches = [img[i:i+patch_size, j:j+patch_size]
           for i in range(0,4,patch_size)
           for j in range(0,4,patch_size)]

print(patches)

[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]]), array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]

## 47.	Implement cosine similarity between two sets of vectors (matrix form, no loops).

In [48]:
A = np.array([[1,0],[0,1]])
B = np.array([[1,1],[1,0]])

dot = A @ B.T
normA = np.linalg.norm(A, axis=1)[:,None]
normB = np.linalg.norm(B, axis=1)

cos_sim = dot / (normA * normB)

print(cos_sim)

[[0.70710678 1.        ]
 [0.70710678 0.        ]]

## 48.	Implement a basic Markov chain transition matrix and compute the stationary distribution via eigenvectors.

In [49]:
P = np.array([[0.9,0.1],[0.5,0.5]])

eig_val, eig_vec = np.linalg.eig(P.T)

stationary = eig_vec[:, np.isclose(eig_val,1)]
stationary = stationary / stationary.sum()

print(stationary.real)

[[0.83333333]
 [0.16666667]]

## 49.	Implement Mean Squared Error and Mean Absolute Error loss functions, both vectorized.

In [50]:
import numpy as np

# Actual and Predicted values
y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])

# MSE
mse = np.mean((y_true - y_pred) ** 2)

# MAE
mae = np.mean(np.abs(y_true - y_pred))

print("MSE:", mse)
print("MAE:", mae)

MSE: 0.375
MAE: 0.5

## 50.	Given your own FusionNet/AMFNet PSNR computation, rewrite it as a single vectorized NumPy function that takes two image batches (batch, H, kl, C) and returns one PSNR value per image in the batch — no Python-level loop over the batch dimension.

In [55]:
# Create two batches of random RGB images
batch_size = 4
H, W, C = 64, 64, 3

img_batch1 = np.random.randint(0, 256, (batch_size, H, W, C), dtype=np.uint8)
img_batch2 = np.random.randint(0, 256, (batch_size, H, W, C), dtype=np.uint8)

# Calculate PSNR
psnr_values = batch_psnr(img_batch1, img_batch2)

print("PSNR Values:")
print(psnr_values)

PSNR Values:
[7.81619701 7.73423508 7.83863745 7.73766314]

# 💡 Real-World Data Science Examples Using NumPy

## 1.	Train/test splitting by generating a shuffled permutation of indices and slicing.

In [89]:
import numpy as np

data = np.arange(10)
np.random.shuffle(data)

split = int(0.8 * len(data))
train, test = data[:split], data[split:]

## 2.	Min-max scaling for neural network inputs (squashing to [0,1] rather than z-score standardizing).

In [94]:
import numpy as np

# Create a NumPy array (e.g., neural network input features)
x = np.array([10, 20, 30])

# Scale the values to the range [0, 1] using Min-Max Scaling
scaled = (x - x.min()) / (x.max() - x.min())

print("Original Values:", x)
print("Scaled Values:", scaled)

Original Values: [10 20 30]
Scaled Values: [0.  0.5 1. ]

## 3.	Computing word/token frequency vectors for a simple bag-of-words NLP feature matrix.

In [95]:
words = np.array(["cat", "dog", "cat", "bird"])

unique, counts = np.unique(words, return_counts=True)
freq = dict(zip(unique, counts))

## 4. Building a co-occurrence matrix for recommendation systems using np.add. at Or array indexing tricks.

In [98]:
import numpy as np

# User-item interactions (user_id, item_id)
interactions = np.array([
    [0, 1],
    [0, 2],
    [1, 1],
    [1, 3],
    [2, 2],
    [2, 3]
])

# Number of items
num_items = 4

# Create an empty co-occurrence matrix
co_matrix = np.zeros((num_items, num_items), dtype=int)

# Build co-occurrence matrix
for user in np.unique(interactions[:, 0]):

    # Get all items purchased by the current user
    items = interactions[interactions[:, 0] == user][:, 1]

    # Increase the count for every item pair
    np.add.at(co_matrix, (items[:, None], items), 1)

print("Co-occurrence Matrix:")
print(co_matrix)

Co-occurrence Matrix:
[[0 0 0 0]
 [0 2 1 1]
 [0 1 2 1]
 [0 1 1 2]]

## 5.	Resizing/cropping image batches via array slicing before feeding into a CNN.

In [100]:
import numpy as np

# Create a batch of 4 RGB images (64x64)
images = np.random.randint(0, 256, (4, 64, 64, 3), dtype=np.uint8)

print("Original Shape:", images.shape)

# Crop the center 32x32 region from each image
cropped_images = images[:, 16:48, 16:48, :]

print("Cropped Shape:", cropped_images.shape)

Original Shape: (4, 64, 64, 3)
Cropped Shape: (4, 32, 32, 3)

## 6. Computing IoU (Intersection over Union) for bounding boxes in object detection — pure vectorized array math.

In [103]:
import numpy as np

# Bounding boxes in the format: [x1, y1, x2, y2]
box1 = np.array([
    [10, 10, 50, 50],
    [20, 20, 60, 60]
])

box2 = np.array([
    [30, 30, 70, 70],
    [25, 25, 55, 55]
])

# Calculate intersection coordinates
x1 = np.maximum(box1[:, 0], box2[:, 0])
y1 = np.maximum(box1[:, 1], box2[:, 1])
x2 = np.minimum(box1[:, 2], box2[:, 2])
y2 = np.minimum(box1[:, 3], box2[:, 3])

# Calculate intersection area
intersection = np.maximum(0, x2 - x1) * np.maximum(0, y2 - y1)

# Calculate individual box areas
area1 = (box1[:, 2] - box1[:, 0]) * (box1[:, 3] - box1[:, 1])
area2 = (box2[:, 2] - box2[:, 0]) * (box2[:, 3] - box2[:, 1])

# Calculate union area
union = area1 + area2 - intersection

# Compute IoU
iou = intersection / union

print("IoU Values:")
print(iou)

IoU Values:
[0.14285714 0.5625    ]

## 7.	Implementing early-stopping logic by tracking a rolling array of validation losses andchecking np. argmin .

In [104]:
import numpy as np

# Validation loss after each epoch
val_loss = np.array([0.85, 0.72, 0.65, 0.61, 0.63, 0.66, 0.68])

# Find the epoch with the lowest validation loss
best_epoch = np.argmin(val_loss)
best_loss = val_loss[best_epoch]

print("Validation Loss:", val_loss)
print("Best Epoch:", best_epoch)
print("Best Validation Loss:", best_loss)

Validation Loss: [0.85 0.72 0.65 0.61 0.63 0.66 0.68]
Best Epoch: 3
Best Validation Loss: 0.61

## 8. Generating synthetic data for testing models ( np. random. normal with controlled mean/variance).

In [106]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Generate 100 synthetic samples
# Mean = 50, Standard Deviation = 10
data = np.random.normal(loc=50, scale=10, size=100)

print("Synthetic Data:")
print(data)

print("\nMean:", np.mean(data))
print("Standard Deviation:", np.std(data))

Synthetic Data:
[54.96714153 48.61735699 56.47688538 65.23029856 47.65846625 47.65863043
 65.79212816 57.67434729 45.30525614 55.42560044 45.36582307 45.34270246
 52.41962272 30.86719755 32.75082167 44.37712471 39.8716888  53.14247333
 40.91975924 35.87696299 64.65648769 47.742237   50.67528205 35.75251814
 44.55617275 51.1092259  38.49006423 53.75698018 43.9936131  47.0830625
 43.98293388 68.52278185 49.86502775 39.42289071 58.22544912 37.7915635
 52.08863595 30.40329876 36.71813951 51.96861236 57.3846658  51.71368281
 48.84351718 46.98896304 35.2147801  42.80155792 45.39361229 60.57122226
 53.4361829  32.36959845 53.24083969 46.1491772  43.23078    56.11676289
 60.30999522 59.31280119 41.60782477 46.90787624 53.31263431 59.75545127
 45.20825762 48.14341023 38.93665026 38.03793376 58.12525822 63.56240029
 49.27989878 60.03532898 53.61636025 43.54880245 53.61395606 65.38036566
 49.64173961 65.64643656 23.80254896 58.21902504 50.87047068 47.0099265
 50.91760777 30.12431085 47.80328112 53.57112572 64.77894045 44.81729782
 41.91506397 44.98242956 59.15402118 53.2875111  44.70239796 55.13267433
 50.97077549 59.68644991 42.97946906 46.72337853 46.07891847 35.36485052
 52.96120277 52.61055272 50.05113457 47.65412867]

Mean: 48.96153482605907
Standard Deviation: 9.036161766446297

## 9. 	Computing a rolling/moving average for time-series smoothing using cumulative sums ( np. cumsum ).

In [107]:
import numpy as np

# Time-series data
data = np.array([10, 20, 30, 40, 50, 60, 70])

# Window size
window = 3

# Compute cumulative sum
cumsum = np.cumsum(data)

# Compute moving average using cumulative sums
moving_avg = (cumsum[window - 1:] - np.concatenate(([0], cumsum[:-window]))) / window

print("Original Data:", data)
print("Moving Average:", moving_avg)

Original Data: [10 20 30 40 50 60 70]
Moving Average: [20. 30. 40. 50. 60.]

## 10. 	Weighted averaging of ensemble model predictions using broadcasting against a weights array.

In [109]:
import numpy as np

# Predictions from 3 models for 5 samples
predictions = np.array([
    [0.80, 0.60, 0.90, 0.70, 0.50],  # Model 1
    [0.75, 0.65, 0.85, 0.72, 0.55],  # Model 2
    [0.90, 0.70, 0.95, 0.68, 0.60]   # Model 3
])

# Weight assigned to each model
weights = np.array([0.5, 0.3, 0.2])

# Compute weighted average using broadcasting
ensemble_prediction = np.sum(predictions * weights[:, np.newaxis], axis=0)

print("Model Predictions:")
print(predictions)

print("\nWeights:")
print(weights)

print("\nEnsemble Prediction:")
print(ensemble_prediction)

Model Predictions:
[[0.8  0.6  0.9  0.7  0.5 ]
 [0.75 0.65 0.85 0.72 0.55]
 [0.9  0.7  0.95 0.68 0.6 ]]

Weights:
[0.5 0.3 0.2]

Ensemble Prediction:
[0.805 0.635 0.895 0.702 0.535]

## 11. Computing per-class precision/recall directly from a confusion matrix using row/column sums.

In [111]:
import numpy as np

# Confusion Matrix
# Rows = Actual Class
# Columns = Predicted Class
conf_matrix = np.array([
    [50, 2, 3],
    [4, 45, 1],
    [2, 3, 40]
])

# True Positives (Diagonal elements)
tp = np.diag(conf_matrix)

# Predicted Positives (Column sums)
predicted = np.sum(conf_matrix, axis=0)

# Actual Positives (Row sums)
actual = np.sum(conf_matrix, axis=1)

# Compute Precision and Recall
precision = tp / predicted
recall = tp / actual

print("Confusion Matrix:\n", conf_matrix)
print("\nPrecision per Class:")
print(precision)

print("\nRecall per Class:")
print(recall)

Confusion Matrix:
 [[50  2  3]
 [ 4 45  1]
 [ 2  3 40]]

Precision per Class:
[0.89285714 0.9        0.90909091]

Recall per Class:
[0.90909091 0.9        0.88888889]

## 12.	Vectorized text-to-numeric encoding — mapping categorical labels to integers via np. un1que( ...  ,  return_1nverse=True) .

In [114]:
import numpy as np

# Categorical labels
labels = np.array(["Cat", "Dog", "Cat", "Bird", "Dog", "Bird", "Cat"])

# Encode labels into integers
unique_labels, encoded_labels = np.unique(labels, return_inverse=True)

print("Original Labels:")
print(labels)

print("\nUnique Labels:")
print(unique_labels)

print("\nEncoded Labels:")
print(encoded_labels)

Original Labels:
['Cat' 'Dog' 'Cat' 'Bird' 'Dog' 'Bird' 'Cat']

Unique Labels:
['Bird' 'Cat' 'Dog']

Encoded Labels:
[1 2 1 0 2 0 1]

## 13	Batch-processing embeddings — computing cosine similarity between a query embedding and a matrix of stored embeddings in one vectorized operation (used in semantic search/recommendation).

In [115]:
import numpy as np

# Query embedding (1 vector)
query = np.array([0.2, 0.4, 0.6])

# Stored embeddings (4 vectors)
embeddings = np.array([
    [0.1, 0.3, 0.5],
    [0.2, 0.5, 0.7],
    [0.9, 0.1, 0.2],
    [0.3, 0.4, 0.6]
])

# Compute dot product
dot_product = embeddings @ query

# Compute vector norms
embedding_norms = np.linalg.norm(embeddings, axis=1)
query_norm = np.linalg.norm(query)

# Compute cosine similarity
cosine_similarity = dot_product / (embedding_norms * query_norm)

print("Cosine Similarity:")
print(cosine_similarity)

Cosine Similarity:
[0.99385869 0.99862543 0.48993186 0.99235957]

## 20.	Computing dataset statistics for a data report — mean , std , min , max , percentiles per column, exactly the kind of summary you'd put in an EDA section of a project report.

In [116]:
import numpy as np

# Sample dataset
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40],
    [25, 35, 45],
    [30, 40, 50]
])

# Compute statistics column-wise
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
minimum = np.min(data, axis=0)
maximum = np.max(data, axis=0)
percentiles = np.percentile(data, [25, 50, 75], axis=0)

print("Mean:", mean)
print("Standard Deviation:", std)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("\n25th Percentile:", percentiles[0])
print("50th Percentile (Median):", percentiles[1])
print("75th Percentile:", percentiles[2])

Mean: [20. 30. 40.]
Standard Deviation: [7.07106781 7.07106781 7.07106781]
Minimum: [10 20 30]
Maximum: [30 40 50]

25th Percentile: [15. 25. 35.]
50th Percentile (Median): [20. 30. 40.]
75th Percentile: [25. 35. 45.]