Name : Anjali Suresh Chopade                                   
Roll_no: 2013

# Example 1: Advertising

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Advertising.csv")
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [3]:
df = pd.read_csv(r"D:\Pandas\All Datasets\Advertising.csv")
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

# Example 2: Claimants Sample

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("claimants sample.csv")
df

   CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0        5       0       1.0         0    50.0  34.940         0
1        3       1       0.0         0    18.0   0.891         1
2       66       0       1.0         0     5.0   0.330         1
3       70       1       1.0         1    31.0   0.037         0
4       96       0       1.0         0    30.0     NaN         1
5       97       1       1.0         0    35.0   0.309         0
6       10       0       NaN         0     9.0   3.538         0
7       36       1       NaN         0    34.0   4.881         0
8       51       1       1.0         0    60.0   0.874         1
9       55       1       1.0         0     NaN   0.350         1

In [6]:
df = pd.read_csv(r"D:\Pandas\All Datasets\claimants sample.csv")
df

   CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0        5       0       1.0         0    50.0  34.940         0
1        3       1       0.0         0    18.0   0.891         1
2       66       0       1.0         0     5.0   0.330         1
3       70       1       1.0         1    31.0   0.037         0
4       96       0       1.0         0    30.0     NaN         1
5       97       1       1.0         0    35.0   0.309         0
6       10       0       NaN         0     9.0   3.538         0
7       36       1       NaN         0    34.0   4.881         0
8       51       1       1.0         0    60.0   0.874         1
9       55       1       1.0         0     NaN   0.350         1

# Example 3: Claimats

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("claimants.csv")
df

      CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0           5     0.0       1.0       0.0    50.0  34.940         0
1           3     1.0       0.0       0.0    18.0   0.891         1
2          66     0.0       1.0       0.0     5.0   0.330         1
3          70     0.0       1.0       1.0    31.0   0.037         0
4          96     0.0       1.0       0.0    30.0   0.038         1
...       ...     ...       ...       ...     ...     ...       ...
1335    34100     0.0       1.0       0.0     NaN   0.576         1
1336    34110     1.0       1.0       0.0    46.0   3.705         0
1337    34113     1.0       1.0       0.0    39.0   0.099         1
1338    34145     1.0       0.0       0.0     8.0   3.177         0
1339    34153     1.0       1.0       0.0    30.0   0.688         1

[1340 rows x 7 columns]

In [9]:
df = pd.read_csv(r"D:\Pandas\All Datasets\claimants.csv")
df

      CASENUM  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS  ATTORNEY
0           5     0.0       1.0       0.0    50.0  34.940         0
1           3     1.0       0.0       0.0    18.0   0.891         1
2          66     0.0       1.0       0.0     5.0   0.330         1
3          70     0.0       1.0       1.0    31.0   0.037         0
4          96     0.0       1.0       0.0    30.0   0.038         1
...       ...     ...       ...       ...     ...     ...       ...
1335    34100     0.0       1.0       0.0     NaN   0.576         1
1336    34110     1.0       1.0       0.0    46.0   3.705         0
1337    34113     1.0       1.0       0.0    39.0   0.099         1
1338    34145     1.0       0.0       0.0     8.0   3.177         0
1339    34153     1.0       1.0       0.0    30.0   0.688         1

[1340 rows x 7 columns]

# Example 4:Gene_expression

In [10]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("gene_expression.csv")
df

      Gene One  Gene Two  Cancer Present
0          4.3       3.9               1
1          2.5       6.3               0
2          5.7       3.9               1
3          6.1       6.2               0
4          7.4       3.4               1
...        ...       ...             ...
2995       5.0       6.5               1
2996       3.4       6.6               0
2997       2.7       6.5               0
2998       3.3       5.6               0
2999       4.6       8.2               0

[3000 rows x 3 columns]

In [13]:
df = pd.read_csv(r"D:\Pandas\All Datasets\gene_expression.csv")
df

      Gene One  Gene Two  Cancer Present
0          4.3       3.9               1
1          2.5       6.3               0
2          5.7       3.9               1
3          6.1       6.2               0
4          7.4       3.4               1
...        ...       ...             ...
2995       5.0       6.5               1
2996       3.4       6.6               0
2997       2.7       6.5               0
2998       3.3       5.6               0
2999       4.6       8.2               0

[3000 rows x 3 columns]

# Example 5:Hearing_test

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("hearing_test.csv")
df

       age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

In [16]:
df = pd.read_csv(r"D:\Pandas\All Datasets\hearing_test.csv")
df

       age  physical_score  test_result
0     33.0            40.7            1
1     50.0            37.2            1
2     52.0            24.7            0
3     56.0            31.0            0
4     35.0            42.9            1
...    ...             ...          ...
4995  73.0             3.9            0
4996  57.0            33.9            1
4997  49.0            34.5            1
4998  38.0            46.4            1
4999  48.0            38.5            1

[5000 rows x 3 columns]

# Example 6: Homeprices

In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv("homeprices.csv")
df

         town  area    price
0     Chennai  2600  5500000
1     Chennai  3000  5650000
2     Chennai  3200  6100000
3     Chennai  3600  6800000
4   Bangalore  2600  5850000
5   Bangalore  2800  6150000
6   Bangalore  3300  6500000
7   Bangalore  3600  7100000
8   Hyderabad  2600  5750000
9   Hyderabad  2900  6000000
10  Hyderabad  3100  6200000
11  Hyderabad  3600  6950000

In [21]:
df = pd.read_csv(r"D:\Pandas\All Datasets\homeprices.csv")
df

         town  area    price
0     Chennai  2600  5500000
1     Chennai  3000  5650000
2     Chennai  3200  6100000
3     Chennai  3600  6800000
4   Bangalore  2600  5850000
5   Bangalore  2800  6150000
6   Bangalore  3300  6500000
7   Bangalore  3600  7100000
8   Hyderabad  2600  5750000
9   Hyderabad  2900  6000000
10  Hyderabad  3100  6200000
11  Hyderabad  3600  6950000

# Example 7: Liver

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv("liver.csv")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

In [24]:
df = pd.read_csv(r"D:\Pandas\All Datasets\liver.csv")
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]

# Example 8: Mouse_viral_study

In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv("mouse_viral_study.csv")
df

     Med_1_mL  Med_2_mL  Virus Present
0    6.508231  8.582531              0
1    4.126116  3.073459              1
2    6.427870  6.369758              0
3    3.672953  4.905215              1
4    1.580321  2.440562              1
..        ...       ...            ...
395  2.884122  3.271748              1
396  7.290855  9.488672              0
397  7.895325  8.272529              0
398  2.690592  2.674979              1
399  7.587821  9.473968              0

[400 rows x 3 columns]

In [27]:
df = pd.read_csv(r"D:\Pandas\All Datasets\mouse_viral_study.csv")
df

     Med_1_mL  Med_2_mL  Virus Present
0    6.508231  8.582531              0
1    4.126116  3.073459              1
2    6.427870  6.369758              0
3    3.672953  4.905215              1
4    1.580321  2.440562              1
..        ...       ...            ...
395  2.884122  3.271748              1
396  7.290855  9.488672              0
397  7.895325  8.272529              0
398  2.690592  2.674979              1
399  7.587821  9.473968              0

[400 rows x 3 columns]

# Example 9: Mushroom

In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("mushrooms.csv")
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [30]:
df = pd.read_csv(r"D:\Pandas\All Datasets\mushrooms.csv")
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

# Example 10: Penguins_size

In [ ]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv("penguins_size.csv")
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [46]:
df = pd.read_csv(r"D:\Pandas\All Datasets\penguins_size.csv")
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

# Example 11: Stroke Prediction

In [43]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv("stroke prediction.csv")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43395,56196,Female,10.0,0,0,No,children,Urban,58.64,20.4,never smoked,0
43396,5450,Female,56.0,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked,0
43397,28375,Female,82.0,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked,0
43398,27973,Male,40.0,0,0,Yes,Private,Urban,99.16,33.2,never smoked,0
43399,36271,Female,82.0,0,0,Yes,Private,Urban,79.48,20.6,never smoked,0

In [48]:
df = pd.read_csv(r"D:\Pandas\All Datasets\stroke prediction.csv")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
43395,56196,Female,10.0,0,0,No,children,Urban,58.64,20.4,never smoked,0
43396,5450,Female,56.0,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked,0
43397,28375,Female,82.0,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked,0
43398,27973,Male,40.0,0,0,Yes,Private,Urban,99.16,33.2,never smoked,0
43399,36271,Female,82.0,0,0,Yes,Private,Urban,79.48,20.6,never smoked,0

# Example 12: Tips

In [44]:
import pandas as pd
import numpy as np

In [49]:
df = pd.read_csv("tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [50]:
df = pd.read_csv(r"D:\Pandas\All Datasets\tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# Example 13: Titanic

In [ ]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [52]:
df = pd.read_csv(r"D:\Pandas\All Datasets\titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# Example 14: Train_test

In [53]:
import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv("train_test.csv")
df

    advitise  sales
0          2     15
1          3     17
2          7     12
3          9      8
4          4      3
5          5      4
6         11      6
7         13      8
8         10     13
9          6     17
10        15      4
11        19      3
12         2      8
13         3      1
14         6     14
15         9     17
16         2     14
17         8     16
18         1     11
19         0     12

In [55]:
df = pd.read_csv(r"D:\Pandas\All Datasets\train_test.csv")
df

    advitise  sales
0          2     15
1          3     17
2          7     12
3          9      8
4          4      3
5          5      4
6         11      6
7         13      8
8         10     13
9          6     17
10        15      4
11        19      3
12         2      8
13         3      1
14         6     14
15         9     17
16         2     14
17         8     16
18         1     11
19         0     12

# Example 15: Boston

In [56]:
import pandas as pd
import numpy as np

In [59]:
df = pd.read_csv("Boston.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [60]:
df = pd.read_csv(r"D:\Pandas\All Datasets\Boston.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500